import { InstrumentOption } from './types';

// List of stocks in NIFTY 50 index
export const NIFTY_50_STOCKS: InstrumentOption[] = [
  { key: 'NSE_EQ|INE423A01024', label: 'ADANIENTERPRISES' },
  { key: 'NSE_EQ|INE742F01042', label: 'ADANIPORTS' },
  { key: 'NSE_EQ|INE437A01024', label: 'APOLLOHOSP' },
  { key: 'NSE_EQ|INE021A01026', label: 'ASIANPAINT' },
  { key: 'NSE_EQ|INE238A01034', label: 'AXISBANK' },
  { key: 'NSE_EQ|INE917I01010', label: 'BAJAJ-AUTO' },
  { key: 'NSE_EQ|INE918I01026', label: 'BAJAJFINSV' },
  { key: 'NSE_EQ|INE296A01024', label: 'BAJFINANCE' },
  { key: 'NSE_EQ|INE263A01024', label: 'BEL' },
  { key: 'NSE_EQ|INE397D01024', label: 'BHARTIARTL' },
  { key: 'NSE_EQ|INE059A01026', label: 'CIPLA' }, 
  { key: 'NSE_EQ|INE522F01014', label: 'COALINDIA' },
  { key: 'NSE_EQ|INE089A01031', label: 'DRREDDY' },
  { key: 'NSE_EQ|INE066A01021', label: 'EICHERMOT' },
  { key: '#N/A', label: 'ETERNAL' },
  { key: 'NSE_EQ|INE047A01021', label: 'GRASIM' },
  { key: 'NSE_EQ|INE860A01027', label: 'HCLTECH' },
  { key: 'NSE_EQ|INE040A01034', label: 'HDFCBANK' },
  { key: 'NSE_EQ|INE795G01014', label: 'HDFCLIFE' },
  { key: 'NSE_EQ|INE158A01026', label: 'HEROMOTOCO' },
  { key: 'NSE_EQ|INE038A01020', label: 'HINDALCO' },
  { key: 'NSE_EQ|INE030A01027', label: 'HINDUNILVR' },
  { key: 'NSE_EQ|INE090A01021', label: 'ICICIBANK' },
  { key: 'NSE_EQ|INE095A01012', label: 'INDUSINDBK' },
  { key: 'NSE_EQ|INE009A01021', label: 'INFY' },
  { key: 'NSE_EQ|INE154A01025', label: 'ITC' },
  { key: 'NSE_EQ|INE758E01017', label: 'JIOFIN' },
  { key: 'NSE_EQ|INE019A01038', label: 'JSWSTEEL' },
  { key: 'NSE_EQ|INE237A01028', label: 'KOTAKBANK' },
  { key: 'NSE_EQ|INE018A01030', label: 'LT' },
  { key: 'NSE_EQ|INE101A01026', label: 'M&M' },
  { key: 'NSE_EQ|INE585B01010', label: 'MARUTI' },
  { key: 'NSE_EQ|INE239A01024', label: 'NESTLEIND' },
  { key: 'NSE_EQ|INE733E01010', label: 'NTPC' },
  { key: 'NSE_EQ|INE213A01029', label: 'ONGC' },
  { key: 'NSE_EQ|INE752E01010', label: 'POWERGRID' },
  { key: 'NSE_EQ|INE002A01018', label: 'RELIANCE' },
  { key: 'NSE_EQ|INE123W01016', label: 'SBILIFE' },
  { key: 'NSE_EQ|INE062A01020', label: 'SBIN' },
  { key: 'NSE_EQ|INE721A01047', label: 'SHRIRAMFIN' },
  { key: 'NSE_EQ|INE044A01036', label: 'SUNPHARMA' },
  { key: 'NSE_EQ|INE192A01025', label: 'TATACONSUM' },
  { key: 'NSE_EQ|INE155A01022', label: 'TATAMOTORS' },
  { key: 'NSE_EQ|INE081A01020', label: 'TATASTEEL' },
  { key: 'NSE_EQ|INE467B01029', label: 'TCS' },
  { key: 'NSE_EQ|INE669C01036', label: 'TECHM' },
  { key: 'NSE_EQ|INE280A01028', label: 'TITAN' },
  { key: 'NSE_EQ|INE849A01020', label: 'TRENT' },
  { key: 'NSE_EQ|INE481G01011', label: 'ULTRACEMCO' },
  { key: 'NSE_EQ|INE075A01022', label: 'WIPRO' },
];

// List of stocks in NIFTY IT index
export const NIFTY_IT_STOCKS: InstrumentOption[] = [
  { key: 'NSE_EQ|INE591G01017', label: 'COFORGE' },
  { key: 'NSE_EQ|INE262H01021', label: 'PERSISTENT' },
  { key: 'NSE_EQ|INE009A01021', label: 'INFY' },
  { key: 'NSE_EQ|INE467B01029', label: 'TCS' },
  { key: 'NSE_EQ|INE881D01027', label: 'OFSS' },
  { key: 'NSE_EQ|INE860A01027', label: 'HCLTECH' },
  { key: 'NSE_EQ|INE356A01018', label: 'MPHASIS' },
  { key: 'NSE_EQ|INE669C01036', label: 'TECHM' },
  { key: 'NSE_EQ|INE214T01019', label: 'LTIM' },
  { key: 'NSE_EQ|INE075A01022', label: 'WIPRO' },
];

// List of stocks in NIFTY MEDIA index
export const NIFTY_MEDIA_STOCKS: InstrumentOption[] = [
  { key: 'NSE_EQ|INE982F01036', label: 'HATHWAY' },
  { key: 'NSE_EQ|INE979A01025', label: 'SAREGAMA' },
  { key: 'NSE_EQ|INE256A01028', label: 'ZEEL' },
  { key: 'NSE_EQ|INE950I01011', label: 'DBCORP' },
  { key: 'NSE_EQ|INE418L01021', label: 'NAZARA' },
  { key: 'NSE_EQ|INE191H01014', label: 'PVRINOX' },
  { key: 'NSE_EQ|INE870H01013', label: 'NETWORK18' },
  { key: 'NSE_EQ|INE716B01029', label: 'TIPSMUSIC' },
  { key: 'NSE_EQ|INE424H01027', label: 'SUNTV' },
  { key: 'NSE_EQ|INE836F01026', label: 'DISHTV' },
];

// List of stocks in NIFTY METAL index
export const NIFTY_METAL_STOCKS: InstrumentOption[] = [
  { key: 'NSE_EQ|INE749A01030', label: 'JINDALSTEL' },
  { key: 'NSE_EQ|INE702C01027', label: 'APLAPOLLO' },
  { key: 'NSE_EQ|INE139A01034', label: 'NATIONALUM' },
  { key: 'NSE_EQ|INE267A01025', label: 'HINDZINC' },
  { key: 'NSE_EQ|INE584A01023', label: 'NMDC' },
  { key: 'NSE_EQ|INE205A01025', label: 'VEDL' },
  { key: 'NSE_EQ|INE281B01032', label: 'LLOYDSME' },
  { key: 'NSE_EQ|INE220G01021', label: 'JSL' },
  { key: 'NSE_EQ|INE081A01020', label: 'TATASTEEL' },
  { key: 'NSE_EQ|INE531E01026', label: 'HINDCOPPER' },
  { key: 'NSE_EQ|INE423A01024', label: 'ADANIENT' },
  { key: 'NSE_EQ|INE019A01038', label: 'JSWSTEEL' },
  { key: 'NSE_EQ|INE038A01020', label: 'HINDALCO' },
  { key: 'NSE_EQ|INE114A01011', label: 'SAIL' },
  { key: 'NSE_EQ|INE191B01025', label: 'WELCORP' },
];

// List of stocks in NIFTY PHARMA index
export const NIFTY_PHARMA_STOCKS: InstrumentOption[] = [
  { key: 'NSE_EQ|INE044A01036', label: 'SUNPHARMA' },
  { key: 'NSE_EQ|INE406A01037', label: 'AUROPHARMA' },
  { key: 'NSE_EQ|INE634S01028', label: 'MANKIND' },
  { key: 'NSE_EQ|INE031B01049', label: 'AJANTPHARM' },
  { key: 'NSE_EQ|INE059A01026', label: 'CIPLA' },
  { key: 'NSE_EQ|INE572A01036', label: 'JBCHEPHARM' },
  { key: 'NSE_EQ|INE010B01027', label: 'ZYDUSLIFE' },
  { key: 'NSE_EQ|INE685A01028', label: 'TORNTPHARM' },
  { key: 'NSE_EQ|INE068V01023', label: 'GLAND' },
  { key: 'NSE_EQ|INE089A01031', label: 'DRREDDY' },
  { key: 'NSE_EQ|INE101D01020', label: 'GRANULES' },
  { key: 'NSE_EQ|INE376G01013', label: 'BIOCON' },
  { key: 'NSE_EQ|INE987B01026', label: 'NATCOPHARM' },
  { key: 'NSE_EQ|INE326A01037', label: 'LUPIN' },
  { key: 'NSE_EQ|INE947Q01028', label: 'LAURUSLABS' },
  { key: 'NSE_EQ|INE540L01014', label: 'ALKEM' },
  { key: 'NSE_EQ|INE358A01014', label: 'ABBOTINDIA' },
  { key: 'NSE_EQ|INE571A01038', label: 'IPCALAB' },
  { key: 'NSE_EQ|INE935A01035', label: 'GLENMARK' },
  { key: 'NSE_EQ|INE361B01024', label: 'DIVISLAB' },
];

// List of stocks in NIFTY PSU BANK index
export const NIFTY_PSU_BANK_STOCKS: InstrumentOption[] = [
  { key: 'NSE_EQ|INE062A01020', label: 'SBIN' },
  { key: 'NSE_EQ|INE457A01014', label: 'MAHABANK' },
  { key: 'NSE_EQ|INE565A01014', label: 'IOB' },
  { key: 'NSE_EQ|INE476A01022', label: 'CANBK' },
  { key: 'NSE_EQ|INE084A01016', label: 'BANKINDIA' },
  { key: 'NSE_EQ|INE562A01011', label: 'INDIANB' },
  { key: 'NSE_EQ|INE691A01018', label: 'UCOBANK' },
  { key: 'NSE_EQ|INE028A01039', label: 'BANKBARODA' },
  { key: 'NSE_EQ|INE160A01022', label: 'PNB' },
  { key: 'NSE_EQ|INE483A01010', label: 'CENTRALBK' },
  { key: 'NSE_EQ|INE608A01012', label: 'PSB' },
  { key: 'NSE_EQ|INE692A01016', label: 'UNIONBANK' },
];

// List of stocks in NIFTY PRIVATE BANK index
export const NIFTY_PRIVATE_BANK_STOCKS: InstrumentOption[] = [
  { key: 'NSE_EQ|INE090A01021', label: 'ICICIBANK' },
  { key: 'NSE_EQ|INE237A01028', label: 'KOTAKBANK' },
  { key: 'NSE_EQ|INE238A01034', label: 'AXISBANK' },
  { key: 'NSE_EQ|INE040A01034', label: 'HDFCBANK' },
  { key: 'NSE_EQ|INE528G01035', label: 'YESBANK' },
  { key: 'NSE_EQ|INE976G01028', label: 'RBLBANK' },
  { key: 'NSE_EQ|INE095A01012', label: 'INDUSINDBK' },
  { key: 'NSE_EQ|INE545U01014', label: 'BANDHANBNK' },
  { key: 'NSE_EQ|INE171A01029', label: 'FEDERALBNK' },
  { key: 'NSE_EQ|INE092T01019', label: 'IDFCFIRSTB' },
];

// List of stocks in NIFTY FINANCIAL SERVICES index
export const NIFTY_FIN_SERVICES_STOCKS: InstrumentOption[] = [
  { key: 'NSE_EQ|INE090A01021', label: 'ICICIBANK' },
  { key: 'NSE_EQ|INE918I01026', label: 'BAJAJFINSV' },
  { key: 'NSE_EQ|INE237A01028', label: 'KOTAKBANK' },
  { key: 'NSE_EQ|INE062A01020', label: 'SBIN' },
  { key: 'NSE_EQ|INE123W01016', label: 'SBILIFE' },
  { key: 'NSE_EQ|INE238A01034', label: 'AXISBANK' },
  { key: 'NSE_EQ|INE721A01047', label: 'SHRIRAMFIN' },
  { key: 'NSE_EQ|INE018E01016', label: 'SBICARD' },
  { key: 'NSE_EQ|INE127D01025', label: 'HDFCAMC' },
  { key: 'NSE_EQ|INE758E01017', label: 'JIOFIN' },
  { key: 'NSE_EQ|INE726G01019', label: 'ICICIPRULI' },
  { key: 'NSE_EQ|INE040A01034', label: 'HDFCBANK' },
  { key: 'NSE_EQ|INE115A01026', label: 'LICHSGFIN' },
  { key: 'NSE_EQ|INE414G01012', label: 'MUTHOOTFIN' },
  { key: 'NSE_EQ|INE296A01024', label: 'BAJFINANCE' },
  { key: 'NSE_EQ|INE020B01018', label: 'RECLTD' },
  { key: 'NSE_EQ|INE795G01014', label: 'HDFCLIFE' },
  { key: 'NSE_EQ|INE134E01011', label: 'PFC' },
  { key: 'NSE_EQ|INE765G01017', label: 'ICICIGI' },
  { key: 'NSE_EQ|INE121A01024', label: 'CHOLAFIN' },
];

// List of stocks in NIFTY REALTY index
export const NIFTY_REALTY_STOCKS: InstrumentOption[] = [
  { key: 'NSE_EQ|INE271C01023', label: 'DLF' },
  { key: 'NSE_EQ|INE211B01039', label: 'PHOENIXLTD' },
  { key: 'NSE_EQ|INE301A01014', label: 'RAYMOND' },
  { key: 'NSE_EQ|INE811K01011', label: 'PRESTIGE' },
  { key: 'NSE_EQ|INE242C01024', label: 'ANANTRAJ' },
  { key: 'NSE_EQ|INE791I01019', label: 'BRIGADE' },
  { key: 'NSE_EQ|INE671H01015', label: 'SOBHA' },
  { key: 'NSE_EQ|INE093I01010', label: 'OBEROIRLTY' },
  { key: 'NSE_EQ|INE484J01027', label: 'GODREJPROP' },
  { key: 'NSE_EQ|INE670K01029', label: 'LODHA' },
];

// List of stocks in NIFTY HEALTHCARE index
export const NIFTY_HEALTHCARE_STOCKS: InstrumentOption[] = [
  { key: 'NSE_EQ|INE044A01036', label: 'SUNPHARMA' },
  { key: 'NSE_EQ|INE406A01037', label: 'AUROPHARMA' },
  { key: 'NSE_EQ|INE634S01028', label: 'MANKIND' },
  { key: 'NSE_EQ|INE061F01013', label: 'FORTIS' },
  { key: 'NSE_EQ|INE059A01026', label: 'CIPLA' },
  { key: 'NSE_EQ|INE010B01027', label: 'ZYDUSLIFE' },
  { key: 'NSE_EQ|INE437A01024', label: 'APOLLOHOSP' },
  { key: 'NSE_EQ|INE685A01028', label: 'TORNTPHARM' },
  { key: 'NSE_EQ|INE027H01010', label: 'MAXHEALTH' },
  { key: 'NSE_EQ|INE089A01031', label: 'DRREDDY' },
  { key: 'NSE_EQ|INE101D01020', label: 'GRANULES' },
  { key: 'NSE_EQ|INE376G01013', label: 'BIOCON' },
  { key: 'NSE_EQ|INE326A01037', label: 'LUPIN' },
  { key: 'NSE_EQ|INE947Q01028', label: 'LAURUSLABS' },
  { key: 'NSE_EQ|INE540L01014', label: 'ALKEM' },
  { key: 'NSE_EQ|INE398R01022', label: 'SYNGENE' },
  { key: 'NSE_EQ|INE358A01014', label: 'ABBOTINDIA' },
  { key: 'NSE_EQ|INE571A01038', label: 'IPCALAB' },
  { key: 'NSE_EQ|INE935A01035', label: 'GLENMARK' },
  { key: 'NSE_EQ|INE361B01024', label: 'DIVISLAB' },
];

// List of stocks in NIFTY FMCG index
export const NIFTY_FMCG_STOCKS: InstrumentOption[] = [
  { key: 'NSE_EQ|INE686F01025', label: 'UBL' },
  { key: 'NSE_EQ|INE239A01024', label: 'NESTLEIND' },
  { key: 'NSE_EQ|INE200M01039', label: 'VBL' },
  { key: 'NSE_EQ|INE192A01025', label: 'TATACONSUM' },
  { key: 'NSE_EQ|INE944F01028', label: 'RADICO' },
  { key: 'NSE_EQ|INE854D01024', label: 'UNITDSPR' },
  { key: 'NSE_EQ|INE216A01030', label: 'BRITANNIA' },
  { key: 'NSE_EQ|INE154A01025', label: 'ITC' },
  { key: 'NSE_EQ|INE259A01022', label: 'COLPAL' },
  { key: 'NSE_EQ|INE030A01027', label: 'HINDUNILVR' },
  { key: 'NSE_EQ|INE102D01028', label: 'GODREJCP' },
  { key: 'NSE_EQ|INE016A01026', label: 'DABUR' },
  { key: 'NSE_EQ|INE196A01026', label: 'MARICO' },
  { key: 'NSE_EQ|INE619A01035', label: 'PATANJALI' },
  { key: 'NSE_EQ|INE548C01032', label: 'EMAMILTD' },
];

// List of stocks in NIFTY 500 index (first part)
export const NIFTY_500_STOCKS: InstrumentOption[] = [
  { key: 'NSE_EQ|INE188A01015', label: 'FACT' },
  { key: 'NSE_EQ|INE168P01015', label: 'EMCURE' },
  { key: 'NSE_EQ|INE148O01028', label: 'DELHIVERY' },
  { key: 'NSE_EQ|INE043W01024', label: 'VIJAYA' },
  { key: 'NSE_EQ|INE128S01021', label: 'FIVESTAR' },
  { key: 'NSE_EQ|INE0Q9301021', label: 'IGIL' },
  { key: 'NSE_EQ|INE824G01012', label: 'JSWHL' },
  { key: 'NSE_EQ|INE138Y01010', label: 'KFINTECH' },
  { key: 'NSE_EQ|INE02RE01045', label: 'FIRSTCRY' },
  { key: '#N/A', label: 'ETERNAL' },
  { key: 'NSE_EQ|INE343G01021', label: 'BHARTIHEXA' },
  { key: 'NSE_EQ|INE019C01026', label: 'HSCL' },
  { key: 'NSE_EQ|INE027A01015', label: 'RCF' },
  { key: 'NSE_EQ|INE149A01033', label: 'CHOLAHLDNG' },
  { key: 'NSE_EQ|INE148I01020', label: 'SAMMAANCAP' },
  { key: 'NSE_EQ|INE450U01017', label: 'ROUTE' },
  { key: 'NSE_EQ|INE377N01017', label: 'WAAREEENER' },
  { key: 'NSE_EQ|INE591G01017', label: 'COFORGE' },
  { key: 'NSE_EQ|INE044A01036', label: 'SUNPHARMA' },
  { key: 'NSE_EQ|INE741K01010', label: 'CREDITACC' },
  { key: 'NSE_EQ|INE090A01021', label: 'ICICIBANK' },
  { key: 'NSE_EQ|INE324A01032', label: 'JINDALSAW' },
  { key: 'NSE_EQ|INE205C01021', label: 'POLYMED' },
  { key: 'NSE_EQ|INE844O01030', label: 'GUJGASLTD' },
  { key: 'NSE_EQ|INE00M201021', label: 'SWSOLAR' },
  { key: 'NSE_EQ|INE117A01022', label: 'ABB' },
  { key: 'NSE_EQ|INE410P01011', label: 'NH' },
  { key: 'NSE_EQ|INE260B01028', label: 'GODFRYPHLP' },
  { key: 'NSE_EQ|INE168A01041', label: 'J&KBANK' },
  { key: 'NSE_EQ|INE397D01024', label: 'BHARTIARTL' },
  { key: 'NSE_EQ|INE406A01037', label: 'AUROPHARMA' },
  { key: 'NSE_EQ|INE749A01030', label: 'JINDALSTEL' },
  { key: 'NSE_EQ|INE118A01012', label: 'BAJAJHLDNG' },
  { key: 'NSE_EQ|INE07Y701011', label: 'POWERINDIA' },
  { key: 'NSE_EQ|INE067A01029', label: 'CGPOWER' },
  { key: 'NSE_EQ|INE192R01011', label: 'DMART' },
  { key: 'NSE_EQ|INE918I01026', label: 'BAJAJFINSV' },
  { key: 'NSE_EQ|INE085A01013', label: 'CHAMBLFERT' },
  { key: 'NSE_EQ|INE930H01031', label: 'KPRMILL' },
  { key: 'NSE_EQ|INE121J01017', label: 'INDUSTOWER' },
  { key: 'NSE_EQ|INE262H01021', label: 'PERSISTENT' },
  { key: 'NSE_EQ|INE498L01015', label: 'LTF' },
  { key: 'NSE_EQ|INE298J01013', label: 'NAM-INDIA' },
  { key: 'NSE_EQ|INE0I7C01011', label: 'LATENTVIEW' },
  { key: 'NSE_EQ|INE237A01028', label: 'KOTAKBANK' },
  { key: 'NSE_EQ|INE00LO01017', label: 'CRAFTSMAN' },
  { key: 'NSE_EQ|INE062A01020', label: 'SBIN' },
  { key: 'NSE_EQ|INE150B01039', label: 'ALKYLAMINE' },
  { key: 'NSE_EQ|INE285K01026', label: 'TECHNOE' },
  { key: 'NSE_EQ|INE206F01022', label: 'AIIL' },
  { key: 'NSE_EQ|INE019A01038', label: 'JSWSTEEL' },
  { key: 'NSE|FACT', label: 'FACT' },
  { key: 'NSE|EMCURE', label: 'EMCURE' },
  { key: 'NSE|DELHIVERY', label: 'DELHIVERY' },
  { key: 'NSE|VIJAYA', label: 'VIJAYA' },
  { key: 'NSE|FIVESTAR', label: 'FIVESTAR' },
  { key: 'NSE|IGIL', label: 'IGIL' },
  { key: 'NSE|JSWHL', label: 'JSWHL' },
  { key: 'NSE|KFINTECH', label: 'KFINTECH' },
  { key: 'NSE|FIRSTCRY', label: 'FIRSTCRY' },
  { key: 'NSE|ETERNAL', label: 'ETERNAL' },
  { key: 'NSE|BHARTIHEXA', label: 'BHARTIHEXA' },
  { key: 'NSE|HSCL', label: 'HSCL' },
  { key: 'NSE|RCF', label: 'RCF' },
  { key: 'NSE|CHOLAHLDNG', label: 'CHOLAHLDNG' },
  { key: 'NSE|SAMMAANCAP', label: 'SAMMAANCAP' },
  { key: 'NSE|ROUTE', label: 'ROUTE' },
  { key: 'NSE|WAAREEENER', label: 'WAAREEENER' },
  { key: 'NSE_EQ|INE591G01017', label: 'COFORGE' },
  { key: 'NSE_EQ|INE044A01036', label: 'SUN PHARMACEUTICAL' },
  { key: 'NSE|CREDITACC', label: 'CREDITACC' },
  { key: 'NSE_EQ|INE090A01021', label: 'ICICI BANK' },
  { key: 'NSE|JINDALSAW', label: 'JINDALSAW' },
  { key: 'NSE|POLYMED', label: 'POLYMED' },
  { key: 'NSE|GUJGASLTD', label: 'GUJGASLTD' },
  { key: 'NSE|SWSOLAR', label: 'SWSOLAR' },
  { key: 'NSE|ABB', label: 'ABB' },
  { key: 'NSE|NH', label: 'NH' },
  { key: 'NSE|GODFRYPHLP', label: 'GODFRYPHLP' },
  { key: 'NSE|J&KBANK', label: 'J&KBANK' },
  { key: 'NSE_EQ|INE397D01024', label: 'BHARTI AIRTEL' },
  { key: 'NSE|AUROPHARMA', label: 'AUROPHARMA' },
  { key: 'NSE|JINDALSTEL', label: 'JINDALSTEL' },
  { key: 'NSE|BAJAJHLDNG', label: 'BAJAJHLDNG' },
  { key: 'NSE|POWERINDIA', label: 'POWERINDIA' },
  { key: 'NSE|CGPOWER', label: 'CGPOWER' },
  { key: 'NSE|DMART', label: 'DMART' },
  { key: 'NSE_EQ|INE918I01026', label: 'BAJAJ FINSERV' },
  { key: 'NSE|CHAMBLFERT', label: 'CHAMBLFERT' },
  { key: 'NSE|KPRMILL', label: 'KPRMILL' },
  { key: 'NSE|INDUSTOWER', label: 'INDUSTOWER' },
  { key: 'NSE_EQ|INE262H01021', label: 'PERSISTENT' },
  { key: 'NSE_EQ|INE018A01030F', label: 'LTF' },
  { key: 'NSE|NAM-INDIA', label: 'NAM-INDIA' },
  { key: 'NSE|LATENTVIEW', label: 'LATENTVIEW' },
  { key: 'NSE_EQ|INE237A01028', label: 'KOTAK MAHINDRA BANK' },
  { key: 'NSE|CRAFTSMAN', label: 'CRAFTSMAN' },
  { key: 'NSE_EQ|INE062A01020', label: 'STATE BANK OF INDIA' },
  { key: 'NSE|ALKYLAMINE', label: 'ALKYLAMINE' },
  { key: 'NSE|TECHNOE', label: 'TECHNOE' },
  { key: 'NSE|AIIL', label: 'AIIL' },
  { key: 'NSE|BAYERCROP', label: 'BAYERCROP' },
  { key: 'NSE_EQ|INE002A01018', label: 'RELIANCE INDUSTRIES' },
  { key: 'NSE_EQ|INE123W01016', label: 'SBI LIFE INSURANCE' },
  { key: 'NSE|NIACL', label: 'NIACL' },
  { key: 'NSE|GRAVITA', label: 'GRAVITA' },
  { key: 'NSE|GICRE', label: 'GICRE' },
  { key: 'NSE|SCHAEFFLER', label: 'SCHAEFFLER' },
  { key: 'NSE_EQ|INE238A01034', label: 'AXIS BANK' },
  { key: 'NSE|PREMIERENE', label: 'PREMIERENE' },
  { key: 'NSE|KAJARIACER', label: 'KAJARIACER' },
  { key: 'NSE|ARE&M', label: 'ARE&M' },
  { key: 'NSE|KEI', label: 'KEI' },
  { key: 'NSE|MAPMYINDIA', label: 'MAPMYINDIA' },
  { key: 'NSE|MANKIND', label: 'MANKIND' },
  { key: 'NSE|GNFC', label: 'GNFC' },
  { key: 'NSE_EQ|INE742F01042', label: 'ADANI PORTS' },
  { key: 'NSE|CAMPUS', label: 'CAMPUS' },
  { key: 'NSE|INDIGO', label: 'INDIGO' },
  { key: 'NSE|DLF', label: 'DLF' },
  { key: 'NSE|ASTRAZEN', label: 'ASTRAZEN' },
  { key: 'NSE_EQ|INE047A01021', label: 'GRASIM INDUSTRIES' },
  { key: 'NSE|ASHOKLEY', label: 'ASHOKLEY' },
  { key: 'NSE|DEEPAKFERT', label: 'DEEPAKFERT' },
  { key: 'NSE|TVSMOTOR', label: 'TVSMOTOR' },
  { key: 'NSE|UNOMINDA', label: 'UNOMINDA' },
  { key: 'NSE|AJANTPHARM', label: 'AJANTPHARM' },
  { key: 'NSE_EQ|INE733E01010GREEN', label: 'NTPCGREEN' },
  { key: 'NSE|HOMEFIRST', label: 'HOMEFIRST' },
  { key: 'NSE_EQ|INE721A01047', label: 'SHRIRAM FINANCE' },
  { key: 'NSE|INDIAMART', label: 'INDIAMART' },
  { key: 'NSE|MOTILALOFS', label: 'MOTILALOFS' },
  { key: 'NSE|NBCC', label: 'NBCC' },
  { key: 'NSE|ADANIENSOL', label: 'ADANIENSOL' },
  { key: 'NSE|SBICARD', label: 'SBI CARDS AND PAYMENT SERVICES' },
  { key: 'NSE|AFFLE', label: 'AFFLE' },
  { key: 'NSE|CRISIL', label: 'CRISIL' },
  { key: 'NSE|FORTIS', label: 'FORTIS' },
  { key: 'NSE|CANFINHOME', label: 'CANFINHOME' },
  { key: 'NSE|CGCL', label: 'CGCL' },
  { key: 'NSE|HUDCO', label: 'HUDCO' },
  { key: 'NSE|HYUNDAI', label: 'HYUNDAI' },
  { key: 'NSE|MAHABANK', label: 'MAHABANK' },
  { key: 'NSE|HDFCAMC', label: 'HDFC ASSET MANAGEMENT COMPANY' },
  { key: 'NSE|UBL', label: 'UBL' },
  { key: 'NSE|MRF', label: 'MRF' },
  { key: 'NSE|KARURVYSYA', label: 'KARURVYSYA' },
  { key: 'NSE|SWIGGY', label: 'SWIGGY' },
  { key: 'NSE|IOB', label: 'IOB' },
  { key: 'NSE|TRENT', label: 'TRENT' },
  { key: 'NSE_EQ|INE758E01017', label: 'JIO FINANCIAL SERVICES' },
  { key: 'NSE|NUVAMA', label: 'NUVAMA' },
  { key: 'NSE|INDIACEM', label: 'INDIACEM' },
  { key: 'NSE|ICICIPRULI', label: 'ICICI PRUDENTIAL LIFE INSURANCE' },
  { key: 'NSE_EQ|INE101A01026', label: 'MAHINDRA & MAHINDRA' },
  { key: 'NSE|GRAPHITE', label: 'GRAPHITE' },
  { key: 'NSE_EQ|INE280A01028', label: 'TITAN COMPANY' },
  { key: 'NSE|OIL', label: 'OIL' },
  { key: 'NSE|ELECON', label: 'ELECON' },
  { key: 'NSE|RAYMONDLSL', label: 'RAYMONDLSL' },
  { key: 'NSE|SAGILITY', label: 'SAGILITY' },
  { key: 'NSE_EQ|INE040A01034', label: 'HDFC BANK' },
  { key: 'NSE_EQ|INE481G01011', label: 'ULTRATECH CEMENT' },
  { key: 'NSE|SAREGAMA', label: 'SAREGAMA' },
  { key: 'NSE|SUZLON', label: 'SUZLON' },
  { key: 'NSE|LICHSGFIN', label: 'LIC HOUSING FINANCE' },
  { key: 'NSE|KIMS', label: 'KIMS' },
  { key: 'NSE_EQ|INE476A01022', label: 'CANARA BANK' },
  { key: 'NSE_EQ|INE239A01024', label: 'NESTLE INDIA' },
  { key: 'NSE|STARHEALTH', label: 'STARHEALTH' },
  { key: 'NSE|CUB', label: 'CUB' },
  { key: 'NSE_EQ|INE018A01030FOODS', label: 'LTFOODS' },
  { key: 'NSE|VTL', label: 'VTL' },
  { key: 'NSE|MAHSEAMLES', label: 'MAHSEAMLES' },
  { key: 'NSE|SYRMA', label: 'SYRMA' },
  { key: 'NSE|MUTHOOTFIN', label: 'MUTHOOT FINANCE' },
  { key: 'NSE|PHOENIXLTD', label: 'PHOENIXLTD' },
  { key: 'NSE_EQ|INE296A01024', label: 'BAJAJ FINANCE' },
  { key: 'NSE|GAIL', label: 'GAIL' },
  { key: 'NSE|VBL', label: 'VBL' },
  { key: 'NSE_EQ|INE733E01010', label: 'NTPC' },
  { key: 'NSE|IRCTC', label: 'IRCTC' },
  { key: 'NSE|SUNDARMFIN', label: 'SUNDARMFIN' },
  { key: 'NSE|NSLNISP', label: 'NSLNISP' },
  { key: 'NSE|BHARATFORG', label: 'BHARATFORG' },
  { key: 'NSE|APLAPOLLO', label: 'APL APOLLO TUBES' },
  { key: 'NSE_EQ|INE059A01026', label: 'CIPLA' },
  { key: 'NSE|TATACONSUM', label: 'TATA CONSUMER PRODUCTS' },
  { key: 'NSE|ABCAPITAL', label: 'ABCAPITAL' },
  { key: 'NSE|APOLLOTYRE', label: 'APOLLOTYRE' },
  { key: 'NSE|HAVELLS', label: 'HAVELLS' },
  { key: 'NSE|JKTYRE', label: 'JKTYRE' },
  { key: 'NSE|JBCHEPHARM', label: 'JBCHEPHARM' },
  { key: 'NSE|NATIONALUM', label: 'NATIONAL ALUMINIUM' },
  { key: 'NSE|SONACOMS', label: 'SONACOMS' },
  { key: 'NSE|YESBANK', label: 'YESBANK' },
  { key: 'NSE|PETRONET', label: 'PETRONET' },
  { key: 'NSE|HONASA', label: 'HONASA' },
  { key: 'NSE|ZYDUSLIFE', label: 'ZYDUS LIFESCIENCES' },
  { key: 'NSE_EQ|INE213A01029', label: 'OIL & NATURAL GAS CORP' },
  { key: 'NSE|BANKINDIA', label: 'BANKINDIA' },
  { key: 'NSE|KIRLOSBROS', label: 'KIRLOSBROS' },
  { key: 'NSE|GMRAIRPORT', label: 'GMRAIRPORT' },
  { key: 'NSE_EQ|INE009A01021', label: 'INFOSYS' },
  { key: 'NSE|CARBORUNIV', label: 'CARBORUNIV' },
  { key: 'NSE|ZEEL', label: 'ZEEL' },
  { key: 'NSE|THERMAX', label: 'THERMAX' },
  { key: 'NSE_EQ|INE437A01024', label: 'APOLLO HOSPITALS' },
  { key: 'NSE|360ONE', label: '360ONE' },
  { key: 'NSE|HFCL', label: 'HFCL' },
  { key: 'NSE|TORNTPHARM', label: 'TORRENT PHARMACEUTICALS' },
  { key: 'NSE|MINDACORP', label: 'MINDACORP' },
  { key: 'NSE|GODIGIT', label: 'GODIGIT' },
  { key: 'NSE|APTUS', label: 'APTUS' },
  { key: 'NSE|POLICYBZR', label: 'POLICYBZR' },
  { key: 'NSE|SOLARINDS', label: 'SOLARINDS' },
  { key: 'NSE|MOTHERSON', label: 'MOTHERSON' },
  { key: 'NSE|RADICO', label: 'RADICO' },
  { key: 'NSE_EQ|INE752E01010', label: 'POWER GRID CORP' },
  { key: 'NSE|RVNL', label: 'RVNL' },
  { key: 'NSE|INDIANB', label: 'INDIANB' },
  { key: 'NSE|INTELLECT', label: 'INTELLECT' },
  { key: 'NSE_EQ|INE101A01026FIN', label: 'M&MFIN' },
  { key: 'NSE|PNCINFRA', label: 'PNCINFRA' },
  { key: 'NSE_EQ|INE066A01021', label: 'EICHER MOTORS' },
  { key: 'NSE|UNITDSPR', label: 'UNITDSPR' },
  { key: 'NSE|TRIDENT', label: 'TRIDENT' },
  { key: 'NSE|GSPL', label: 'GSPL' },
  { key: 'NSE|IDEA', label: 'IDEA' },
  { key: 'NSE|ADANIPOWER', label: 'ADANIPOWER' },
  { key: 'NSE_EQ|INE155A01022', label: 'TATA MOTORS' },
  { key: 'NSE|CDSL', label: 'CDSL' },
  { key: 'NSE|TANLA', label: 'TANLA' },
  { key: 'NSE|VMM', label: 'VMM' },
  { key: 'NSE|JUSTDIAL', label: 'JUSTDIAL' },
  { key: 'NSE|BIKAJI', label: 'BIKAJI' },
  { key: 'NSE|RAYMOND', label: 'RAYMOND' },
  { key: 'NSE|SIGNATURE', label: 'SIGNATURE' },
  { key: 'NSE|RITES', label: 'RITES' },
  { key: 'NSE|IDBI', label: 'IDBI' },
  { key: 'NSE|UCOBANK', label: 'UCOBANK' },
  { key: 'NSE_EQ|INE467B01029', label: 'TATA CONSULTANCY SERVICES' },
  { key: 'NSE|MANAPPURAM', label: 'MANAPPURAM' },
  { key: 'NSE|IOC', label: 'IOC' },
  { key: 'NSE|BRITANNIA', label: 'BRITANNIA' },
  { key: 'NSE|JMFINANCIL', label: 'JMFINANCIL' },
  { key: 'NSE|UTIAMC', label: 'UTIAMC' },
  { key: 'NSE|RBLBANK', label: 'RBLBANK' },
  { key: 'NSE_EQ|INE881D01027', label: 'ORACLE FINANCIAL SERVICES' },
  { key: 'NSE|MFSL', label: 'MFSL' },
  { key: 'NSE|DALBHARAT', label: 'DALBHARAT' },
  { key: 'NSE|JBMA', label: 'JBMA' },
  { key: 'NSE|RPOWER', label: 'RPOWER' },
  { key: 'NSE|SHREECEM', label: 'SHREECEM' },
  { key: 'NSE|WOCKPHARMA', label: 'WOCKPHARMA' },
  { key: 'NSE|EIHOTEL', label: 'EIHOTEL' },
  { key: 'NSE|RECLTD', label: 'REC' },
  { key: 'NSE_EQ|INE949L01017', label: 'AU SMALL FINANCE BANK' },
  { key: 'NSE|PRESTIGE', label: 'PRESTIGE' },
  { key: 'NSE_EQ|INE028A01039', label: 'BANK OF BARODA' },
  { key: 'NSE_EQ|INE154A01025', label: 'ITC' },
  { key: 'NSE|COLPAL', label: 'COLPAL' },
  { key: 'NSE|ESCORTS', label: 'ESCORTS' },
  { key: 'NSE_EQ|INE917I01010', label: 'BAJAJ AUTO' },
  { key: 'NSE|MCX', label: 'MCX' },
  { key: 'NSE|HINDZINC', label: 'HINDZINC' },
  { key: 'NSE_EQ|INE095A01012', label: 'INDUSIND BANK' },
  { key: 'NSE_EQ|INE160A01022', label: 'PUNJAB NATIONAL BANK' },
  { key: 'NSE|ANANTRAJ', label: 'ANANTRAJ' },
  { key: 'NSE|TIMKEN', label: 'TIMKEN' },
  { key: 'NSE|MAXHEALTH', label: 'MAXHEALTH' },
  { key: 'NSE|VOLTAS', label: 'VOLTAS' },
  { key: 'NSE|AMBUJACEM', label: 'AMBUJA CEMENTS' },
  { key: 'NSE_EQ|INE018A01030', label: 'LARSEN & TOUBRO' },
  { key: 'NSE|MMTC', label: 'MMTC' },
  { key: 'NSE_EQ|INE860A01027', label: 'HCL TECHNOLOGIES' },
  { key: 'NSE|LICI', label: 'LICI' },
  { key: 'NSE|RRKABEL', label: 'RRKABEL' },
  { key: 'NSE|OLECTRA', label: 'OLECTRA' },
  { key: 'NSE|CYIENT', label: 'CYIENT' },
  { key: 'NSE|IEX', label: 'IEX' },
  { key: 'NSE|GMDCLTD', label: 'GMDCLTD' },
  { key: 'NSE|NEULANDLAB', label: 'NEULANDLAB' },
  { key: 'NSE|JPPOWER', label: 'JPPOWER' },
  { key: 'NSE|SHYAMMETL', label: 'SHYAMMETL' },
  { key: 'NSE|IKS', label: 'IKS' },
  { key: 'NSE|BHEL', label: 'BHEL' },
  { key: 'NSE|LEMONTREE', label: 'LEMONTREE' },
  { key: 'NSE|BOSCHLTD', label: 'BOSCHLTD' },
  { key: 'NSE|GRANULES', label: 'GRANULES INDIA' },
  { key: 'NSE_EQ|INE089A01031', label: 'DR REDDY\'S LABS' },
  { key: 'NSE_EQ|INE795G01014', label: 'HDFC LIFE INSURANCE' },
  { key: 'NSE|IRB', label: 'IRB' },
  { key: 'NSE|BLS', label: 'BLS' },
  { key: 'NSE|BALKRISIND', label: 'BALKRISIND' },
  { key: 'NSE|ABFRL', label: 'ABFRL' },
  { key: 'NSE|DIXON', label: 'DIXON' },
  { key: 'NSE|PIDILITIND', label: 'PIDILITIND' },
  { key: 'NSE|BIOCON', label: 'BIOCON' },
  { key: 'NSE|TATAPOWER', label: 'TATAPOWER' },
  { key: 'NSE|DOMS', label: 'DOMS' },
  { key: 'NSE|PEL', label: 'PEL' },
  { key: 'NSE_EQ|INE356A01018', label: 'MPHASIS' },
  { key: 'NSE|TATAINVEST', label: 'TATAINVEST' },
  { key: 'NSE|JUBLPHARMA', label: 'JUBLPHARMA' },
  { key: 'NSE|KPIL', label: 'KPIL' },
  { key: 'NSE_EQ|INE263A01024', label: 'BHARAT ELECTRONICS' },
  { key: 'NSE|IRFC', label: 'IRFC' },
  { key: 'NSE|NMDC', label: 'NMDC' },
  { key: 'NSE|CENTRALBK', label: 'CENTRALBK' },
  { key: 'NSE|SKFINDIA', label: 'SKFINDIA' },
  { key: 'NSE|BRIGADE', label: 'BRIGADE' },
  { key: 'NSE|VEDL', label: 'VEDANTA' },
  { key: 'NSE|IGL', label: 'IGL' },
  { key: 'NSE|LLOYDSME', label: 'LLOYDSME' },
  { key: 'NSE|HAL', label: 'HAL' },
  { key: 'NSE_EQ|INE030A01027', label: 'HINDUSTAN UNILEVER' },
  { key: 'NSE|JWL', label: 'JWL' },
  { key: 'NSE|BANDHANBNK', label: 'BANDHANBNK' },
  { key: 'NSE|IIFL', label: 'IIFL' },
  { key: 'NSE|PVRINOX', label: 'PVRINOX' },
  { key: 'NSE|COCHINSHIP', label: 'COCHINSHIP' },
  { key: 'NSE|DATAPATTNS', label: 'DATAPATTNS' },
  { key: 'NSE|JSL', label: 'JINDAL STAINLESS' },
  { key: 'NSE|IFCI', label: 'IFCI' },
  { key: 'NSE|HONAUT', label: 'HONAUT' },
  { key: 'NSE_EQ|INE021A01026', label: 'ASIAN PAINTS' },
  { key: 'NSE_EQ|INE081A01020', label: 'TATA STEEL' },
  { key: 'NSE|BERGEPAINT', label: 'BERGEPAINT' },
  { key: 'NSE|AADHARHFC', label: 'AADHARHFC' },
  { key: 'NSE|NATCOPHARM', label: 'NATCOPHARM' },
  { key: 'NSE|PAGEIND', label: 'PAGEIND' },
  { key: 'NSE|RAILTEL', label: 'RAILTEL' },
  { key: 'NSE|SCI', label: 'SCI' },
  { key: 'NSE|HINDCOPPER', label: 'HINDUSTAN COPPER' },
  { key: 'NSE|DEVYANI', label: 'DEVYANI' },
  { key: 'NSE|RENUKA', label: 'RENUKA' },
  { key: 'NSE|GODREJIND', label: 'GODREJIND' },
  { key: 'NSE|HBLENGINE', label: 'HBLENGINE' },
  { key: 'NSE|DCMSHRIRAM', label: 'DCMSHRIRAM' },
  { key: 'NSE|NYKAA', label: 'NYKAA' },
  { key: 'NSE|POONAWALLA', label: 'POONAWALLA' },
  { key: 'NSE|CONCOR', label: 'CONCOR' },
  { key: 'NSE|GILLETTE', label: 'GILLETTE' },
  { key: 'NSE|GPPL', label: 'GPPL' },
  { key: 'NSE|FLUOROCHEM', label: 'FLUOROCHEM' },
  { key: 'NSE|ADANIGREEN', label: 'ADANIGREEN' },
  { key: 'NSE_EQ|INE171A01029', label: 'FEDERAL BANK' },
  { key: 'NSE|CESC', label: 'CESC' },
  { key: 'NSE|JKCEMENT', label: 'JKCEMENT' },
  { key: 'NSE|ACC', label: 'ACC' },
  { key: 'NSE|BLUEDART', label: 'BLUEDART' },
  { key: 'NSE|BSE', label: 'BSE' },
  { key: 'NSE_EQ|INE585B01010', label: 'MARUTI SUZUKI' },
  { key: 'NSE|PCBL', label: 'PCBL' },
  { key: 'NSE|RTNINDIA', label: 'RTNINDIA' },
  { key: 'NSE|LUPIN', label: 'LUPIN' },
  { key: 'NSE|OLAELEC', label: 'OLAELEC' },
  { key: 'NSE|WHIRLPOOL', label: 'WHIRLPOOL' },
  { key: 'NSE_EQ|INE423A01024', label: 'ADANI ENTERPRISES' },
  { key: 'NSE|MGL', label: 'MGL' },
  { key: 'NSE|LINDEINDIA', label: 'LINDEINDIA' },
  { key: 'NSE|TATACHEM', label: 'TATACHEM' },
  { key: 'NSE|ANANDRATHI', label: 'ANANDRATHI' },
  { key: 'NSE|SRF', label: 'SRF' },
  { key: 'NSE|SIEMENS', label: 'SIEMENS' },
  { key: 'NSE_EQ|INE522F01014', label: 'COAL INDIA' },
  { key: 'NSE|PFC', label: 'POWER FINANCE CORPORATION' },
  { key: 'NSE|LAURUSLABS', label: 'LAURUS LABS' },
  { key: 'NSE|ATGL', label: 'ATGL' },
  { key: 'NSE|IRCON', label: 'IRCON' },
  { key: 'NSE|SCHNEIDER', label: 'SCHNEIDER' },
  { key: 'NSE|HAPPSTMNDS', label: 'HAPPSTMNDS' },
  { key: 'NSE|CEATLTD', label: 'CEATLTD' },
  { key: 'NSE|METROPOLIS', label: 'METROPOLIS' },
  { key: 'NSE|RAMCOCEM', label: 'RAMCOCEM' },
  { key: 'NSE|INDHOTEL', label: 'INDHOTEL' },
  { key: 'NSE_EQ|INE019A01038', label: 'JSW STEEL' },
  { key: 'NSE|ANGELONE', label: 'ANGELONE' },
  { key: 'NSE_EQ|INE018A01030TS', label: 'LTTS' },
  { key: 'NSE|CUMMINSIND', label: 'CUMMINSIND' },
  { key: 'NSE|ALKEM', label: 'ALKEM LABORATORIES' },
  { key: 'NSE|FINPIPE', label: 'FINPIPE' },
  { key: 'NSE|ELGIEQUIP', label: 'ELGIEQUIP' },
  { key: 'NSE|MSUMI', label: 'MSUMI' },
  { key: 'NSE|SYNGENE', label: 'SYNGENE' },
  { key: 'NSE|ABBOTINDIA', label: 'ABBOTINDIA' },
  { key: 'NSE|BPCL', label: 'BPCL' },
  { key: 'NSE|POLYCAB', label: 'POLYCAB' },
  { key: 'NSE|TITAGARH', label: 'TITAGARH' },
  { key: 'NSE|ABREL', label: 'ABREL' },
  { key: 'NSE|BBTC', label: 'BBTC' },
  { key: 'NSE_EQ|INE158A01026', label: 'HERO MOTOCORP' },
  { key: 'NSE|JSWENERGY', label: 'JSWENERGY' },
  { key: 'NSE|TIINDIA', label: 'TIINDIA' },
  { key: 'NSE|NLCINDIA', label: 'NLCINDIA' },
  { key: 'NSE_EQ|INE669C01036', label: 'TECH MAHINDRA' },
  { key: 'NSE|AWL', label: 'AWL' },
  { key: 'NSE|GLAXO', label: 'GLAXO' },
  { key: 'NSE_EQ|INE038A01020', label: 'HINDALCO INDUSTRIES' },
  { key: 'NSE|PIIND', label: 'PIIND' },
  { key: 'NSE|APLLTD', label: 'APLLTD' },
  { key: 'NSE|KNRCON', label: 'KNRCON' },
  { key: 'NSE|KANSAINER', label: 'KANSAINER' },
  { key: 'NSE|AAVAS', label: 'AAVAS' },
  { key: 'NSE|GODREJCP', label: 'GODREJCP' },
  { key: 'NSE|ASAHIINDIA', label: 'ASAHIINDIA' },
  { key: 'NSE|FINCABLES', label: 'FINCABLES' },
  { key: 'NSE|CAMS', label: 'CAMS' },
  { key: 'NSE|ZENSARTECH', label: 'ZENSARTECH' },
  { key: 'NSE|GRSE', label: 'GRSE' },
  { key: 'NSE|DABUR', label: 'DABUR' },
  { key: 'NSE|EXIDEIND', label: 'EXIDEIND' },
  { key: 'NSE|BEML', label: 'BEML' },
  { key: 'NSE|NHPC', label: 'NHPC' },
  { key: 'NSE|MASTEK', label: 'MASTEK' },
  { key: 'NSE|SOBHA', label: 'SOBHA' },
  { key: 'NSE|ASTERDM', label: 'ASTERDM' },
  { key: 'NSE|BSOFT', label: 'BSOFT' },
  { key: 'NSE|WESTLIFE', label: 'WESTLIFE' },
  { key: 'NSE|KALYANKJIL', label: 'KALYANKJIL' },
  { key: 'NSE|OBEROIRLTY', label: 'OBEROIRLTY' },
  { key: 'NSE|SUPREMEIND', label: 'SUPREMEIND' },
  { key: 'NSE|NIVABUPA', label: 'NIVABUPA' },
  { key: 'NSE|TATATECH', label: 'TATATECH' },
  { key: 'NSE|NETWORK18', label: 'NETWORK18' },
  { key: 'NSE|JYOTHYLAB', label: 'JYOTHYLAB' },
  { key: 'NSE|FSL', label: 'FSL' },
  { key: 'NSE|WELSPUNLIV', label: 'WELSPUNLIV' },
  { key: 'NSE|JYOTICNC', label: 'JYOTICNC' },
  { key: 'NSE|INOXINDIA', label: 'INOXINDIA' },
  { key: 'NSE|CERA', label: 'CERA' },
  { key: 'NSE|GODREJPROP', label: 'GODREJPROP' },
  { key: 'NSE|BDL', label: 'BDL' },
  { key: 'NSE_EQ|INE092T01019', label: 'IDFC FIRST BANK' },
  { key: 'NSE|ATUL', label: 'ATUL' },
  { key: 'NSE|NAUKRI', label: 'NAUKRI' },
  { key: 'NSE|TRITURBINE', label: 'TRITURBINE' },
  { key: 'NSE|RAINBOW', label: 'RAINBOW' },
  { key: 'NSE|ASTRAL', label: 'ASTRAL' },
  { key: 'NSE|UNIONBANK', label: 'UNIONBANK' },
  { key: 'NSE|KAYNES', label: 'KAYNES' },
  { key: 'NSE|TTML', label: 'TTML' },
  { key: 'NSE|AMBER', label: 'AMBER' },
  { key: 'NSE|COROMANDEL', label: 'COROMANDEL' },
  { key: 'NSE|TATAELXSI', label: 'TATAELXSI' },
  { key: 'NSE|SBFC', label: 'SBFC' },
  { key: 'NSE|UPL', label: 'UPL' },
  { key: 'NSE|AFCONS', label: 'AFCONS' },
  { key: 'NSE|LODHA', label: 'LODHA' },
  { key: 'NSE|SWANENERGY', label: 'SWANENERGY' },
  { key: 'NSE|DEEPAKNTR', label: 'DEEPAKNTR' },
  { key: 'NSE|HEG', label: 'HEG' },
  { key: 'NSE|CLEAN', label: 'CLEAN' },
  { key: 'NSE|ACMESOLAR', label: 'ACMESOLAR' },
  { key: 'NSE|HINDPETRO', label: 'HINDPETRO' },
  { key: 'NSE|KPITTECH', label: 'KPITTECH' },
  { key: 'NSE|ALOKINDS', label: 'ALOKINDS' },
  { key: 'NSE|BATAINDIA', label: 'BATAINDIA' },
  { key: 'NSE|PFIZER', label: 'PFIZER' },
  { key: 'NSE|MAZDOCK', label: 'MAZDOCK' },
  { key: 'NSE|CROMPTON', label: 'CROMPTON' },
  { key: 'NSE|EIDPARRY', label: 'EIDPARRY' },
  { key: 'NSE|TORNTPOWER', label: 'TORNTPOWER' },
  { key: 'NSE|ECLERX', label: 'ECLERX' },
  { key: 'NSE|TEJASNET', label: 'TEJASNET' },
  { key: 'NSE|SUMICHEM', label: 'SUMICHEM' },
  { key: 'NSE|MARICO', label: 'MARICO' },
  { key: 'NSE|SJVN', label: 'SJVN' },
  { key: 'NSE|INDGN', label: 'INDGN' },
  { key: 'NSE|PPLPHARMA', label: 'PPLPHARMA' },
  { key: 'NSE|NAVINFLUOR', label: 'NAVINFLUOR' },
  { key: 'NSE|ERIS', label: 'ERIS' },
  { key: 'NSE|JSWINFRA', label: 'JSWINFRA' },
  { key: 'NSE|PRAJIND', label: 'PRAJIND' },
  { key: 'NSE|MANYAVAR', label: 'MANYAVAR' },
  { key: 'NSE|ZFCVINDIA', label: 'ZFCVINDIA' },
  { key: 'NSE|BASF', label: 'BASF' },
  { key: 'NSE|MRPL', label: 'MRPL' },
  { key: 'NSE|CAPLIPOINT', label: 'CAPLIPOINT' },
  { key: 'NSE|IPCALAB', label: 'IPCA LABORATORIES' },
  { key: 'NSE|SUNDRMFAST', label: 'SUNDRMFAST' },
  { key: 'NSE|BAJAJHFL', label: 'BAJAJHFL' },
  { key: 'NSE|PGEL', label: 'PGEL' },
  { key: 'NSE|JUBLFOOD', label: 'JUBLFOOD' },
  { key: 'NSE|AARTIIND', label: 'AARTIIND' },
  { key: 'NSE_EQ|INE160A01022HOUSING', label: 'PNBHOUSING' },
  { key: 'NSE|GESHIP', label: 'GESHIP' },
  { key: 'NSE|ZENTEC', label: 'ZENTEC' },
  { key: 'NSE|REDINGTON', label: 'REDINGTON' },
  { key: 'NSE|INOXWIND', label: 'INOXWIND' },
  { key: 'NSE|ITI', label: 'ITI' },
  { key: 'NSE|ICICIGI', label: 'ICICI LOMBARD GENERAL INSURANCE' },
  { key: 'NSE|ALIVUS', label: 'ALIVUS' },
  { key: 'NSE|GVT&D', label: 'GVT&D' },
  { key: 'NSE|AIAENG', label: 'AIAENG' },
  { key: 'NSE|ACE', label: 'ACE' },
  { key: 'NSE|ENGINERSIN', label: 'ENGINERSIN' },
  { key: 'NSE|GODREJAGRO', label: 'GODREJAGRO' },
  { key: 'NSE|JUBLINGREA', label: 'JUBLINGREA' },
  { key: 'NSE|TRIVENI', label: 'TRIVENI' },
  { key: 'NSE|GLENMARK', label: 'GLENMARK' },
  { key: 'NSE|CONCORDBIO', label: 'CONCORDBIO' },
  { key: 'NSE|CENTURYPLY', label: 'CENTURYPLY' },
  { key: 'NSE|NETWEB', label: 'NETWEB' },
  { key: 'NSE|DBREALTY', label: 'DBREALTY' },
  { key: 'NSE_EQ|INE018A01030IM', label: 'LTI MINDTREE' },
  { key: 'NSE|CHOLAFIN', label: 'CHOLAMANDALAM INVESTMENT' },
  { key: 'NSE|GPIL', label: 'GPIL' },
  { key: 'NSE|PATANJALI', label: 'PATANJALI' },
  { key: 'NSE|SAIL', label: 'STEEL AUTHORITY OF INDIA' },
  { key: 'NSE|KIRLOSENG', label: 'KIRLOSENG' },
  { key: 'NSE|NCC', label: 'NCC' },
  { key: 'NSE|ABSLAMC', label: 'ABSLAMC' },
  { key: 'NSE|CHENNPETRO', label: 'CHENNPETRO' },
  { key: 'NSE|CHALET', label: 'CHALET' },
  { key: 'NSE|SAPPHIRE', label: 'SAPPHIRE' },
  { key: 'NSE|SARDAEN', label: 'SARDAEN' },
  { key: 'NSE|KEC', label: 'KEC' },
  { key: 'NSE|TATACOMM', label: 'TATACOMM' },
  { key: 'NSE|3MINDIA', label: '3MINDIA' },
  { key: 'NSE|IREDA', label: 'IREDA' },
  { key: 'NSE|BLUESTARCO', label: 'BLUESTARCO' },
  { key: 'NSE|SAILIFE', label: 'SAILIFE' },
  { key: 'NSE|EMAMILTD', label: 'EMAMILTD' },
  { key: 'NSE|APARINDS', label: 'APARINDS' },
  { key: 'NSE|MEDANTA', label: 'MEDANTA' },
  { key: 'NSE|PTCIL', label: 'PTCIL' },
  { key: 'NSE|CASTROLIND', label: 'CASTROLIND' },
  { key: 'NSE|WELCORP', label: 'WELSPUN CORP' },
  { key: 'NSE|NEWGEN', label: 'NEWGEN' },
  { key: 'NSE|PAYTM', label: 'PAYTM' },
  { key: 'NSE|BALRAMCHIN', label: 'BALRAMCHIN' },
  { key: 'NSE|ENDURANCE', label: 'ENDURANCE' },
  { key: 'NSE|TBOTEK', label: 'TBOTEK' },
  { key: 'NSE|CCL', label: 'CCL' },
  { key: 'NSE|DIVISLAB', label: 'DIVI\'S LABORATORIES' },
  { key: 'NSE|LALPATHLAB', label: 'LALPATHLAB' },
  { key: 'NSE|VGUARD', label: 'VGUARD' },
  { key: 'NSE|AEGISLOG', label: 'AEGISLOG' },
  { key: 'NSE|USHAMART', label: 'USHAMART' },
  { key: 'NSE|SUVENPHAR', label: 'SUVENPHAR' },
  { key: 'NSE|SUNTV', label: 'SUNTV' },
  { key: 'NSE|AKUMS', label: 'AKUMS' },
  { key: 'NSE|RHIM', label: 'RHIM' },
  { key: 'NSE|NAVA', label: 'NAVA' },
  { key: 'NSE|TARIL', label: 'TARIL' },
  { key: 'NSE|RKFORGE', label: 'RKFORGE' },
  { key: 'NSE_EQ|INE075A01022', label: 'WIPRO' },
  { key: 'NSE|SONATSOFTW', label: 'SONATSOFTW' },
  { key: 'NSE_EQ|INE462A01022', label: 'BAYERCROP' },
  { key: 'NSE_EQ|INE002A01018', label: 'RELIANCE' },
  { key: 'NSE_EQ|INE123W01016', label: 'SBILIFE' },
  { key: 'NSE_EQ|INE470Y01017', label: 'NIACL' },
  { key: 'NSE_EQ|INE024L01027', label: 'GRAVITA' },
  { key: 'NSE_EQ|INE481Y01014', label: 'GICRE' },
  { key: 'NSE_EQ|INE513A01022', label: 'SCHAEFFLER' },
  { key: 'NSE_EQ|INE238A01034', label: 'AXISBANK' },
  { key: 'NSE_EQ|INE0BS701011', label: 'PREMIERENE' },
  { key: 'NSE_EQ|INE217B01036', label: 'KAJARIACER' },
  { key: 'NSE_EQ|INE885A01032', label: 'ARE&M' },
  { key: 'NSE_EQ|INE878B01027', label: 'KEI' },
  { key: 'NSE_EQ|INE0BV301023', label: 'MAPMYINDIA' },
  { key: 'NSE_EQ|INE634S01028', label: 'MANKIND' },
  { key: 'NSE_EQ|INE113A01013', label: 'GNFC' },
  { key: 'NSE_EQ|INE742F01042', label: 'ADANIPORTS' },
  { key: 'NSE_EQ|INE278Y01022', label: 'CAMPUS' },
  { key: 'NSE_EQ|INE646L01027', label: 'INDIGO' },
  { key: 'NSE_EQ|INE271C01023', label: 'DLF' },
  { key: 'NSE_EQ|INE203A01020', label: 'ASTRAZEN' },
  { key: 'NSE_EQ|INE047A01021', label: 'GRASIM' },
  { key: 'NSE_EQ|INE208A01029', label: 'ASHOKLEY' },
  { key: 'NSE_EQ|INE501A01019', label: 'DEEPAKFERT' },
  { key: 'NSE_EQ|INE494B01023', label: 'TVSMOTOR' },
  { key: 'NSE_EQ|INE405E01023', label: 'UNOMINDA' },
  { key: 'NSE_EQ|INE031B01049', label: 'AJANTPHARM' },
  { key: 'NSE_EQ|INE0ONG01011', label: 'NTPCGREEN' },
  { key: 'NSE_EQ|INE481N01025', label: 'HOMEFIRST' },
  { key: 'NSE_EQ|INE721A01047', label: 'SHRIRAMFIN' },
  { key: 'NSE_EQ|INE933S01016', label: 'INDIAMART' },
  { key: 'NSE_EQ|INE338I01027', label: 'MOTILALOFS' },
  { key: 'NSE_EQ|INE095N01031', label: 'NBCC' },
  { key: 'NSE_EQ|INE931S01010', label: 'ADANIENSOL' },
  { key: 'NSE_EQ|INE018E01016', label: 'SBICARD' },
  { key: 'NSE_EQ|INE00WC01027', label: 'AFFLE' },
  { key: 'NSE_EQ|INE007A01025', label: 'CRISIL' },
  { key: 'NSE_EQ|INE061F01013', label: 'FORTIS' },
  { key: 'NSE_EQ|INE477A01020', label: 'CANFINHOME' },
  { key: 'NSE_EQ|INE180C01042', label: 'CGCL' },
  { key: 'NSE_EQ|INE031A01017', label: 'HUDCO' },
  { key: 'NSE_EQ|INE0V6F01027', label: 'HYUNDAI' },
  { key: 'NSE_EQ|INE457A01014', label: 'MAHABANK' },
  { key: 'NSE_EQ|INE127D01025', label: 'HDFCAMC' },
  { key: 'NSE_EQ|INE686F01025', label: 'UBL' },
  { key: 'NSE_EQ|INE883A01011', label: 'MRF' },
  { key: 'NSE_EQ|INE036D01028', label: 'KARURVYSYA' },
  { key: 'NSE_EQ|INE00H001014', label: 'SWIGGY' },
  { key: 'NSE_EQ|INE565A01014', label: 'IOB' },
  { key: 'NSE_EQ|INE849A01020', label: 'TRENT' },
  { key: 'NSE_EQ|INE758E01017', label: 'JIOFIN' },
  { key: 'NSE_EQ|INE531F01015', label: 'NUVAMA' },
  { key: 'NSE_EQ|INE383A01012', label: 'INDIACEM' },
  { key: 'NSE_EQ|INE726G01019', label: 'ICICIPRULI' },
  { key: 'NSE_EQ|INE101A01026', label: 'M&M' },
  { key: 'NSE_EQ|INE371A01025', label: 'GRAPHITE' },
  { key: 'NSE_EQ|INE280A01028', label: 'TITAN' },
  { key: 'NSE_EQ|INE274J01014', label: 'OIL' },
  { key: 'NSE_EQ|INE205B01031', label: 'ELECON' },
  { key: 'NSE_EQ|INE02ID01020', label: 'RAYMONDLSL' },
  { key: 'NSE_EQ|INE0W2G01015', label: 'SAGILITY' },
  { key: 'NSE_EQ|INE040A01034', label: 'HDFCBANK' },
  { key: 'NSE_EQ|INE481G01011', label: 'ULTRACEMCO' },
  { key: 'NSE_EQ|INE979A01025', label: 'SAREGAMA' },
  { key: 'NSE_EQ|INE040H01021', label: 'SUZLON' },
  { key: 'NSE_EQ|INE115A01026', label: 'LICHSGFIN' },
  { key: 'NSE_EQ|INE967H01025', label: 'KIMS' },
  { key: 'NSE_EQ|INE476A01022', label: 'CANBK' },
  { key: 'NSE_EQ|INE239A01024', label: 'NESTLE INDIA' },
  { key: 'NSE_EQ|INE575P01011', label: 'STARHEALTH' },
  { key: 'NSE_EQ|INE491A01021', label: 'CUB' },
  { key: 'NSE_EQ|INE818H01020', label: 'LTFOODS' },
  { key: 'NSE_EQ|INE825A01020', label: 'VTL' },
  { key: 'NSE_EQ|INE271B01025', label: 'MAHSEAMLES' },
  { key: 'NSE_EQ|INE0DYJ01015', label: 'SYRMA' },
  { key: 'NSE_EQ|INE414G01012', label: 'MUTHOOTFIN' },
  { key: 'NSE_EQ|INE211B01039', label: 'PHOENIXLTD' },
  { key: 'NSE_EQ|INE296A01024', label: 'BAJFINANCE' },
  { key: 'NSE_EQ|INE129A01019', label: 'GAIL' },
  { key: 'NSE_EQ|INE200M01039', label: 'VBL' },
  { key: 'NSE_EQ|INE733E01010', label: 'NTPC' },
  { key: 'NSE_EQ|INE335Y01020', label: 'IRCTC' },
  { key: 'NSE_EQ|INE660A01013', label: 'SUNDARMFIN' },
  { key: 'NSE_EQ|INE0NNS01018', label: 'NSLNISP' },
  { key: 'NSE_EQ|INE465A01025', label: 'BHARATFORG' },
  { key: 'NSE_EQ|INE702C01027', label: 'APLAPOLLO' },
  { key: 'NSE_EQ|INE059A01026', label: 'CIPLA' },
  { key: 'NSE_EQ|INE192A01025', label: 'TATACONSUM' },
  { key: 'NSE_EQ|INE674K01013', label: 'ABCAPITAL' },
  { key: 'NSE_EQ|INE438A01022', label: 'APOLLOTYRE' },
  { key: 'NSE_EQ|INE176B01034', label: 'HAVELLS' },
  { key: 'NSE_EQ|INE573A01042', label: 'JKTYRE' },
  { key: 'NSE_EQ|INE572A01036', label: 'JBCHEPHARM' },
  { key: 'NSE_EQ|INE139A01034', label: 'NATIONALUM' },
  { key: 'NSE_EQ|INE073K01018', label: 'SONACOMS' },
  { key: 'NSE_EQ|INE528G01035', label: 'YESBANK' },
  { key: 'NSE_EQ|INE347G01014', label: 'PETRONET' },
  { key: 'NSE_EQ|INE0J5401028', label: 'HONASA' },
  { key: 'NSE_EQ|INE010B01027', label: 'ZYDUSLIFE' },
  { key: 'NSE_EQ|INE213A01029', label: 'ONGC' },
  { key: 'NSE_EQ|INE084A01016', label: 'BANKINDIA' },
  { key: 'NSE_EQ|INE732A01036', label: 'KIRLOSBROS' },
  { key: 'NSE_EQ|INE776C01039', label: 'GMRAIRPORT' },
  { key: 'NSE_EQ|INE009A01021', label: 'INFY' },
  { key: 'NSE_EQ|INE120A01034', label: 'CARBORUNIV' },
  { key: 'NSE_EQ|INE256A01028', label: 'ZEEL' },
  { key: 'NSE_EQ|INE152A01029', label: 'THERMAX' },
  { key: 'NSE_EQ|INE437A01024', label: 'APOLLOHOSP' },
  { key: 'NSE_EQ|INE466L01038', label: '360ONE' },
  { key: 'NSE_EQ|INE548A01028', label: 'HFCL' },
  { key: 'NSE_EQ|INE685A01028', label: 'TORNTPHARM' },
  { key: 'NSE_EQ|INE842C01021', label: 'MINDACORP' },
  { key: 'NSE_EQ|INE03JT01014', label: 'GODIGIT' },
  { key: 'NSE_EQ|INE852O01025', label: 'APTUS' },
  { key: 'NSE_EQ|INE417T01026', label: 'POLICYBZR' },
  { key: 'NSE_EQ|INE343H01029', label: 'SOLARINDS' },
  { key: 'NSE_EQ|INE775A08105', label: 'MOTHERSON' },
  { key: 'NSE_EQ|INE944F01028', label: 'RADICO' },
  { key: 'NSE_EQ|INE752E01010', label: 'POWER GRID CORP' },
  { key: 'NSE|RVNL', label: 'RVNL' },
  { key: 'NSE|INDIANB', label: 'INDIANB' },
  { key: 'NSE|INTELLECT', label: 'INTELLECT' },
  { key: 'NSE_EQ|INE101A01026FIN', label: 'M&MFIN' },
  { key: 'NSE|PNCINFRA', label: 'PNCINFRA' },
  { key: 'NSE_EQ|INE066A01021', label: 'EICHER MOTORS' },
  { key: 'NSE|UNITDSPR', label: 'UNITDSPR' },
  { key: 'NSE|TRIDENT', label: 'TRIDENT' },
  { key: 'NSE|GSPL', label: 'GSPL' },
  { key: 'NSE|IDEA', label: 'IDEA' },
  { key: 'NSE|ADANIPOWER', label: 'ADANIPOWER' },
  { key: 'NSE_EQ|INE155A01022', label: 'TATA MOTORS' },
  { key: 'NSE|CDSL', label: 'CDSL' },
  { key: 'NSE|TANLA', label: 'TANLA' },
  { key: 'NSE|VMM', label: 'VMM' },
  { key: 'NSE|JUSTDIAL', label: 'JUSTDIAL' },
  { key: 'NSE|BIKAJI', label: 'BIKAJI' },
  { key: 'NSE|RAYMOND', label: 'RAYMOND' },
  { key: 'NSE|SIGNATURE', label: 'SIGNATURE' },
  { key: 'NSE|RITES', label: 'RITES' },
  { key: 'NSE|IDBI', label: 'IDBI' },
  { key: 'NSE|UCOBANK', label: 'UCOBANK' },
  { key: 'NSE_EQ|INE467B01029', label: 'TATA CONSULTANCY SERVICES' },
  { key: 'NSE|MANAPPURAM', label: 'MANAPPURAM' },
  { key: 'NSE|IOC', label: 'IOC' },
  { key: 'NSE|BRITANNIA', label: 'BRITANNIA' },
  { key: 'NSE|JMFINANCIL', label: 'JMFINANCIL' },
  { key: 'NSE|UTIAMC', label: 'UTIAMC' },
  { key: 'NSE|RBLBANK', label: 'RBLBANK' },
  { key: 'NSE_EQ|INE881D01027', label: 'ORACLE FINANCIAL SERVICES' },
  { key: 'NSE|MFSL', label: 'MFSL' },
  { key: 'NSE|DALBHARAT', label: 'DALBHARAT' },
  { key: 'NSE|JBMA', label: 'JBMA' },
  { key: 'NSE|RPOWER', label: 'RPOWER' },
  { key: 'NSE|SHREECEM', label: 'SHREECEM' },
  { key: 'NSE|WOCKPHARMA', label: 'WOCKPHARMA' },
  { key: 'NSE|EIHOTEL', label: 'EIHOTEL' },
  { key: 'NSE|RECLTD', label: 'REC' },
  { key: 'NSE_EQ|INE949L01017', label: 'AU SMALL FINANCE BANK' },
  { key: 'NSE|PRESTIGE', label: 'PRESTIGE' },
  { key: 'NSE_EQ|INE028A01039', label: 'BANK OF BARODA' },
  { key: 'NSE_EQ|INE154A01025', label: 'ITC' },
  { key: 'NSE|COLPAL', label: 'COLPAL' },
  { key: 'NSE|ESCORTS', label: 'ESCORTS' },
  { key: 'NSE_EQ|INE917I01010', label: 'BAJAJ AUTO' },
  { key: 'NSE|MCX', label: 'MCX' },
  { key: 'NSE|HINDZINC', label: 'HINDZINC' },
  { key: 'NSE_EQ|INE095A01012', label: 'INDUSIND BANK' },
  { key: 'NSE_EQ|INE160A01022', label: 'PUNJAB NATIONAL BANK' },
  { key: 'NSE|ANANTRAJ', label: 'ANANTRAJ' },
  { key: 'NSE|TIMKEN', label: 'TIMKEN' },
  { key: 'NSE|MAXHEALTH', label: 'MAXHEALTH' },
  { key: 'NSE|VOLTAS', label: 'VOLTAS' },
  { key: 'NSE|AMBUJACEM', label: 'AMBUJA CEMENTS' },
  { key: 'NSE_EQ|INE018A01030', label: 'LARSEN & TOUBRO' },
  { key: 'NSE|MMTC', label: 'MMTC' },
  { key: 'NSE_EQ|INE860A01027', label: 'HCL TECHNOLOGIES' },
  { key: 'NSE|LICI', label: 'LICI' },
  { key: 'NSE|RRKABEL', label: 'RRKABEL' },
  { key: 'NSE|OLECTRA', label: 'OLECTRA' },
  { key: 'NSE|CYIENT', label: 'CYIENT' },
  { key: 'NSE|IEX', label: 'IEX' },
  { key: 'NSE|GMDCLTD', label: 'GMDCLTD' },
  { key: 'NSE|NEULANDLAB', label: 'NEULANDLAB' },
  { key: 'NSE|JPPOWER', label: 'JPPOWER' },
  { key: 'NSE|SHYAMMETL', label: 'SHYAMMETL' },
  { key: 'NSE|IKS', label: 'IKS' },
  { key: 'NSE|BHEL', label: 'BHEL' },
  { key: 'NSE|LEMONTREE', label: 'LEMONTREE' },
  { key: 'NSE|BOSCHLTD', label: 'BOSCHLTD' },
  { key: 'NSE|GRANULES', label: 'GRANULES INDIA' },
  { key: 'NSE_EQ|INE089A01031', label: 'DR REDDY\'S LABS' },
  { key: 'NSE_EQ|INE795G01014', label: 'HDFC LIFE INSURANCE' },
  { key: 'NSE|IRB', label: 'IRB' },
  { key: 'NSE|BLS', label: 'BLS' },
  { key: 'NSE|BALKRISIND', label: 'BALKRISIND' },
  { key: 'NSE|ABFRL', label: 'ABFRL' },
  { key: 'NSE|DIXON', label: 'DIXON' },
  { key: 'NSE|PIDILITIND', label: 'PIDILITIND' },
  { key: 'NSE|BIOCON', label: 'BIOCON' },
  { key: 'NSE|TATAPOWER', label: 'TATAPOWER' },
  { key: 'NSE|DOMS', label: 'DOMS' },
  { key: 'NSE|PEL', label: 'PEL' },
  { key: 'NSE_EQ|INE356A01018', label: 'MPHASIS' },
  { key: 'NSE|TATAINVEST', label: 'TATAINVEST' },
  { key: 'NSE|JUBLPHARMA', label: 'JUBLPHARMA' },
  { key: 'NSE|KPIL', label: 'KPIL' },
  { key: 'NSE_EQ|INE263A01024', label: 'BHARAT ELECTRONICS' },
  { key: 'NSE|IRFC', label: 'IRFC' },
  { key: 'NSE|NMDC', label: 'NMDC' },
  { key: 'NSE|CENTRALBK', label: 'CENTRALBK' },
  { key: 'NSE|SKFINDIA', label: 'SKFINDIA' },
  { key: 'NSE|BRIGADE', label: 'BRIGADE' },
  { key: 'NSE|VEDL', label: 'VEDANTA' },
  { key: 'NSE|IGL', label: 'IGL' },
  { key: 'NSE|LLOYDSME', label: 'LLOYDSME' },
  { key: 'NSE|HAL', label: 'HAL' },
  { key: 'NSE_EQ|INE030A01027', label: 'HINDUSTAN UNILEVER' },
  { key: 'NSE|JWL', label: 'JWL' },
  { key: 'NSE|BANDHANBNK', label: 'BANDHANBNK' },
  { key: 'NSE|IIFL', label: 'IIFL' },
  { key: 'NSE|PVRINOX', label: 'PVRINOX' },
  { key: 'NSE|COCHINSHIP', label: 'COCHINSHIP' },
  { key: 'NSE|DATAPATTNS', label: 'DATAPATTNS' },
  { key: 'NSE|JSL', label: 'JINDAL STAINLESS' },
  { key: 'NSE|IFCI', label: 'IFCI' },
  { key: 'NSE|HONAUT', label: 'HONAUT' },
  { key: 'NSE_EQ|INE021A01026', label: 'ASIAN PAINTS' },
  { key: 'NSE_EQ|INE081A01020', label: 'TATA STEEL' },
  { key: 'NSE|BERGEPAINT', label: 'BERGEPAINT' },
  { key: 'NSE|AADHARHFC', label: 'AADHARHFC' },
  { key: 'NSE|NATCOPHARM', label: 'NATCOPHARM' },
  { key: 'NSE|PAGEIND', label: 'PAGEIND' },
  { key: 'NSE|RAILTEL', label: 'RAILTEL' },
  { key: 'NSE|SCI', label: 'SCI' },
  { key: 'NSE|HINDCOPPER', label: 'HINDUSTAN COPPER' },
  { key: 'NSE|DEVYANI', label: 'DEVYANI' },
  { key: 'NSE|RENUKA', label: 'RENUKA' },
  { key: 'NSE|GODREJIND', label: 'GODREJIND' },
  { key: 'NSE|HBLENGINE', label: 'HBLENGINE' },
  { key: 'NSE|DCMSHRIRAM', label: 'DCMSHRIRAM' },
  { key: 'NSE|NYKAA', label: 'NYKAA' },
  { key: 'NSE|POONAWALLA', label: 'POONAWALLA' },
  { key: 'NSE|CONCOR', label: 'CONCOR' },
  { key: 'NSE|GILLETTE', label: 'GILLETTE' },
  { key: 'NSE|GPPL', label: 'GPPL' },
  { key: 'NSE|FLUOROCHEM', label: 'FLUOROCHEM' },
  { key: 'NSE|ADANIGREEN', label: 'ADANIGREEN' },
  { key: 'NSE_EQ|INE171A01029', label: 'FEDERAL BANK' },
  { key: 'NSE|CESC', label: 'CESC' },
  { key: 'NSE|JKCEMENT', label: 'JKCEMENT' },
  { key: 'NSE|ACC', label: 'ACC' },
  { key: 'NSE|BLUEDART', label: 'BLUEDART' },
  { key: 'NSE|BSE', label: 'BSE' },
  { key: 'NSE_EQ|INE585B01010', label: 'MARUTI SUZUKI' },
  { key: 'NSE|PCBL', label: 'PCBL' },
  { key: 'NSE|RTNINDIA', label: 'RTNINDIA' },
  { key: 'NSE|LUPIN', label: 'LUPIN' },
  { key: 'NSE|OLAELEC', label: 'OLAELEC' },
  { key: 'NSE|WHIRLPOOL', label: 'WHIRLPOOL' },
  { key: 'NSE_EQ|INE423A01024', label: 'ADANI ENTERPRISES' },
  { key: 'NSE|MGL', label: 'MGL' },
  { key: 'NSE|LINDEINDIA', label: 'LINDEINDIA' },
  { key: 'NSE|TATACHEM', label: 'TATACHEM' },
  { key: 'NSE|ANANDRATHI', label: 'ANANDRATHI' },
  { key: 'NSE|SRF', label: 'SRF' },
  { key: 'NSE|SIEMENS', label: 'SIEMENS' },
  { key: 'NSE_EQ|INE522F01014', label: 'COAL INDIA' },
  { key: 'NSE|PFC', label: 'POWER FINANCE CORPORATION' },
  { key: 'NSE|LAURUSLABS', label: 'LAURUS LABS' },
  { key: 'NSE|ATGL', label: 'ATGL' },
  { key: 'NSE|IRCON', label: 'IRCON' },
  { key: 'NSE|SCHNEIDER', label: 'SCHNEIDER' },
  { key: 'NSE|HAPPSTMNDS', label: 'HAPPSTMNDS' },
  { key: 'NSE|CEATLTD', label: 'CEATLTD' },
  { key: 'NSE|METROPOLIS', label: 'METROPOLIS' },
  { key: 'NSE|RAMCOCEM', label: 'RAMCOCEM' },
  { key: 'NSE|INDHOTEL', label: 'INDHOTEL' },
  { key: 'NSE_EQ|INE019A01038', label: 'JSW STEEL' },
  { key: 'NSE|ANGELONE', label: 'ANGELONE' },
  { key: 'NSE_EQ|INE018A01030TS', label: 'LTTS' },
  { key: 'NSE|CUMMINSIND', label: 'CUMMINSIND' },
  { key: 'NSE|ALKEM', label: 'ALKEM LABORATORIES' },
  { key: 'NSE|FINPIPE', label: 'FINPIPE' },
  { key: 'NSE|ELGIEQUIP', label: 'ELGIEQUIP' },
  { key: 'NSE|MSUMI', label: 'MSUMI' },
  { key: 'NSE|SYNGENE', label: 'SYNGENE' },
  { key: 'NSE|ABBOTINDIA', label: 'ABBOTINDIA' },
  { key: 'NSE|BPCL', label: 'BPCL' },
  { key: 'NSE|POLYCAB', label: 'POLYCAB' },
  { key: 'NSE|TITAGARH', label: 'TITAGARH' },
  { key: 'NSE|ABREL', label: 'ABREL' },
  { key: 'NSE|BBTC', label: 'BBTC' },
  { key: 'NSE_EQ|INE158A01026', label: 'HERO MOTOCORP' },
  { key: 'NSE|JSWENERGY', label: 'JSWENERGY' },
  { key: 'NSE|TIINDIA', label: 'TIINDIA' },
  { key: 'NSE|NLCINDIA', label: 'NLCINDIA' },
  { key: 'NSE_EQ|INE669C01036', label: 'TECH MAHINDRA' },
  { key: 'NSE|AWL', label: 'AWL' },
  { key: 'NSE|GLAXO', label: 'GLAXO' },
  { key: 'NSE_EQ|INE038A01020', label: 'HINDALCO INDUSTRIES' },
  { key: 'NSE|PIIND', label: 'PIIND' },
  { key: 'NSE|APLLTD', label: 'APLLTD' },
  { key: 'NSE|KNRCON', label: 'KNRCON' },
  { key: 'NSE|KANSAINER', label: 'KANSAINER' },
  { key: 'NSE|AAVAS', label: 'AAVAS' },
  { key: 'NSE|GODREJCP', label: 'GODREJCP' },
  { key: 'NSE|ASAHIINDIA', label: 'ASAHIINDIA' },
  { key: 'NSE|FINCABLES', label: 'FINCABLES' },
  { key: 'NSE|CAMS', label: 'CAMS' },
  { key: 'NSE|ZENSARTECH', label: 'ZENSARTECH' },
  { key: 'NSE|GRSE', label: 'GRSE' },
  { key: 'NSE|DABUR', label: 'DABUR' },
  { key: 'NSE|EXIDEIND', label: 'EXIDEIND' },
  { key: 'NSE|BEML', label: 'BEML' },
  { key: 'NSE|NHPC', label: 'NHPC' },
  { key: 'NSE|MASTEK', label: 'MASTEK' },
  { key: 'NSE|SOBHA', label: 'SOBHA' },
  { key: 'NSE|ASTERDM', label: 'ASTERDM' },
  { key: 'NSE|BSOFT', label: 'BSOFT' },
  { key: 'NSE|WESTLIFE', label: 'WESTLIFE' },
  { key: 'NSE|KALYANKJIL', label: 'KALYANKJIL' },
  { key: 'NSE|OBEROIRLTY', label: 'OBEROIRLTY' },
  { key: 'NSE|SUPREMEIND', label: 'SUPREMEIND' },
  { key: 'NSE|NIVABUPA', label: 'NIVABUPA' },
  { key: 'NSE|TATATECH', label: 'TATATECH' },
  { key: 'NSE|NETWORK18', label: 'NETWORK18' },
  { key: 'NSE|JYOTHYLAB', label: 'JYOTHYLAB' },
  { key: 'NSE|FSL', label: 'FSL' },
  { key: 'NSE|WELSPUNLIV', label: 'WELSPUNLIV' },
  { key: 'NSE|JYOTICNC', label: 'JYOTICNC' },
  { key: 'NSE|INOXINDIA', label: 'INOXINDIA' },
  { key: 'NSE|CERA', label: 'CERA' },
  { key: 'NSE|GODREJPROP', label: 'GODREJPROP' },
  { key: 'NSE|BDL', label: 'BDL' },
  { key: 'NSE_EQ|INE092T01019', label: 'IDFC FIRST BANK' },
  { key: 'NSE|ATUL', label: 'ATUL' },
  { key: 'NSE|NAUKRI', label: 'NAUKRI' },
  { key: 'NSE|TRITURBINE', label: 'TRITURBINE' },
  { key: 'NSE|RAINBOW', label: 'RAINBOW' },
  { key: 'NSE|ASTRAL', label: 'ASTRAL' },
  { key: 'NSE|UNIONBANK', label: 'UNIONBANK' },
  { key: 'NSE|KAYNES', label: 'KAYNES' },
  { key: 'NSE|TTML', label: 'TTML' },
  { key: 'NSE|AMBER', label: 'AMBER' },
  { key: 'NSE|COROMANDEL', label: 'COROMANDEL' },
  { key: 'NSE|TATAELXSI', label: 'TATAELXSI' },
  { key: 'NSE|SBFC', label: 'SBFC' },
  { key: 'NSE|UPL', label: 'UPL' },
  { key: 'NSE|AFCONS', label: 'AFCONS' },
  { key: 'NSE|LODHA', label: 'LODHA' },
  { key: 'NSE|SWANENERGY', label: 'SWANENERGY' },
  { key: 'NSE|DEEPAKNTR', label: 'DEEPAKNTR' },
  { key: 'NSE|HEG', label: 'HEG' },
  { key: 'NSE|CLEAN', label: 'CLEAN' },
  { key: 'NSE|ACMESOLAR', label: 'ACMESOLAR' },
  { key: 'NSE|HINDPETRO', label: 'HINDPETRO' },
  { key: 'NSE|KPITTECH', label: 'KPITTECH' },
  { key: 'NSE|ALOKINDS', label: 'ALOKINDS' },
  { key: 'NSE|BATAINDIA', label: 'BATAINDIA' },
  { key: 'NSE|PFIZER', label: 'PFIZER' },
  { key: 'NSE|MAZDOCK', label: 'MAZDOCK' },
  { key: 'NSE|CROMPTON', label: 'CROMPTON' },
  { key: 'NSE|EIDPARRY', label: 'EIDPARRY' },
  { key: 'NSE|TORNTPOWER', label: 'TORNTPOWER' },
  { key: 'NSE|ECLERX', label: 'ECLERX' },
  { key: 'NSE|TEJASNET', label: 'TEJASNET' },
  { key: 'NSE|SUMICHEM', label: 'SUMICHEM' },
  { key: 'NSE|MARICO', label: 'MARICO' },
  { key: 'NSE|SJVN', label: 'SJVN' },
  { key: 'NSE|INDGN', label: 'INDGN' },
  { key: 'NSE|PPLPHARMA', label: 'PPLPHARMA' },
  { key: 'NSE|NAVINFLUOR', label: 'NAVINFLUOR' },
  { key: 'NSE|ERIS', label: 'ERIS' },
  { key: 'NSE|JSWINFRA', label: 'JSWINFRA' },
  { key: 'NSE|PRAJIND', label: 'PRAJIND' },
  { key: 'NSE|MANYAVAR', label: 'MANYAVAR' },
  { key: 'NSE|ZFCVINDIA', label: 'ZFCVINDIA' },
  { key: 'NSE|BASF', label: 'BASF' },
  { key: 'NSE|MRPL', label: 'MRPL' },
  { key: 'NSE|CAPLIPOINT', label: 'CAPLIPOINT' },
  { key: 'NSE|IPCALAB', label: 'IPCA LABORATORIES' },
  { key: 'NSE|SUNDRMFAST', label: 'SUNDRMFAST' },
  { key: 'NSE|BAJAJHFL', label: 'BAJAJHFL' },
  { key: 'NSE|PGEL', label: 'PGEL' },
  { key: 'NSE|JUBLFOOD', label: 'JUBLFOOD' },
  { key: 'NSE|AARTIIND', label: 'AARTIIND' },
  { key: 'NSE_EQ|INE160A01022HOUSING', label: 'PNBHOUSING' },
  { key: 'NSE|GESHIP', label: 'GESHIP' },
  { key: 'NSE|ZENTEC', label: 'ZENTEC' },
  { key: 'NSE|REDINGTON', label: 'REDINGTON' },
  { key: 'NSE|INOXWIND', label: 'INOXWIND' },
  { key: 'NSE|ITI', label: 'ITI' },
  { key: 'NSE|ICICIGI', label: 'ICICI LOMBARD GENERAL INSURANCE' },
  { key: 'NSE|ALIVUS', label: 'ALIVUS' },
  { key: 'NSE|GVT&D', label: 'GVT&D' },
  { key: 'NSE|AIAENG', label: 'AIAENG' },
  { key: 'NSE|ACE', label: 'ACE' },
  { key: 'NSE|ENGINERSIN', label: 'ENGINERSIN' },
  { key: 'NSE|GODREJAGRO', label: 'GODREJAGRO' },
  { key: 'NSE|JUBLINGREA', label: 'JUBLINGREA' },
  { key: 'NSE|TRIVENI', label: 'TRIVENI' },
  { key: 'NSE|GLENMARK', label: 'GLENMARK' },
  { key: 'NSE|CONCORDBIO', label: 'CONCORDBIO' },
  { key: 'NSE|CENTURYPLY', label: 'CENTURYPLY' },
  { key: 'NSE|NETWEB', label: 'NETWEB' },
  { key: 'NSE|DBREALTY', label: 'DBREALTY' },
  { key: 'NSE_EQ|INE018A01030IM', label: 'LTI MINDTREE' },
  { key: 'NSE|CHOLAFIN', label: 'CHOLAMANDALAM INVESTMENT' },
  { key: 'NSE|GPIL', label: 'GPIL' },
  { key: 'NSE|PATANJALI', label: 'PATANJALI' },
  { key: 'NSE|SAIL', label: 'STEEL AUTHORITY OF INDIA' },
  { key: 'NSE|KIRLOSENG', label: 'KIRLOSENG' },
  { key: 'NSE|NCC', label: 'NCC' },
  { key: 'NSE|ABSLAMC', label: 'ABSLAMC' },
  { key: 'NSE|CHENNPETRO', label: 'CHENNPETRO' },
  { key: 'NSE|CHALET', label: 'CHALET' },
  { key: 'NSE|SAPPHIRE', label: 'SAPPHIRE' },
  { key: 'NSE|SARDAEN', label: 'SARDAEN' },
  { key: 'NSE|KEC', label: 'KEC' },
  { key: 'NSE|TATACOMM', label: 'TATACOMM' },
  { key: 'NSE|3MINDIA', label: '3MINDIA' },
  { key: 'NSE|IREDA', label: 'IREDA' },
  { key: 'NSE|BLUESTARCO', label: 'BLUESTARCO' },
  { key: 'NSE|SAILIFE', label: 'SAILIFE' },
  { key: 'NSE|EMAMILTD', label: 'EMAMILTD' },
  { key: 'NSE|APARINDS', label: 'APARINDS' },
  { key: 'NSE|MEDANTA', label: 'MEDANTA' },
  { key: 'NSE|PTCIL', label: 'PTCIL' },
  { key: 'NSE|CASTROLIND', label: 'CASTROLIND' },
  { key: 'NSE|WELCORP', label: 'WELSPUN CORP' },
  { key: 'NSE|NEWGEN', label: 'NEWGEN' },
  { key: 'NSE|PAYTM', label: 'PAYTM' },
  { key: 'NSE|BALRAMCHIN', label: 'BALRAMCHIN' },
  { key: 'NSE|ENDURANCE', label: 'ENDURANCE' },
  { key: 'NSE|TBOTEK', label: 'TBOTEK' },
  { key: 'NSE|CCL', label: 'CCL' },
  { key: 'NSE|DIVISLAB', label: 'DIVI\'S LABORATORIES' },
  { key: 'NSE|LALPATHLAB', label: 'LALPATHLAB' },
  { key: 'NSE|VGUARD', label: 'VGUARD' },
  { key: 'NSE|AEGISLOG', label: 'AEGISLOG' },
  { key: 'NSE|USHAMART', label: 'USHAMART' },
  { key: 'NSE|SUVENPHAR', label: 'SUVENPHAR' },
  { key: 'NSE|SUNTV', label: 'SUNTV' },
  { key: 'NSE|AKUMS', label: 'AKUMS' },
  { key: 'NSE|RHIM', label: 'RHIM' },
  { key: 'NSE|NAVA', label: 'NAVA' },
  { key: 'NSE|TARIL', label: 'TARIL' },
  { key: 'NSE|RKFORGE', label: 'RKFORGE' },
  { key: 'NSE_EQ|INE075A01022', label: 'WIPRO' },
  { key: 'NSE|SONATSOFTW', label: 'SONATSOFTW' },
  { key: 'NSE_EQ|INE462A01022', label: 'BAYERCROP' },
  { key: 'NSE_EQ|INE002A01018', label: 'RELIANCE' },
  { key: 'NSE_EQ|INE123W01016', label: 'SBILIFE' },
  { key: 'NSE_EQ|INE470Y01017', label: 'NIACL' },
  { key: 'NSE_EQ|INE024L01027', label: 'GRAVITA' },
  { key: 'NSE_EQ|INE481Y01014', label: 'GICRE' },
  { key: 'NSE_EQ|INE513A01022', label: 'SCHAEFFLER' },
  { key: 'NSE_EQ|INE238A01034', label: 'AXISBANK' },
  { key: 'NSE_EQ|INE0BS701011', label: 'PREMIERENE' },
  { key: 'NSE_EQ|INE217B01036', label: 'KAJARIACER' },
  { key: 'NSE_EQ|INE885A01032', label: 'ARE&M' },
  { key: 'NSE_EQ|INE878B01027', label: 'KEI' },
  { key: 'NSE_EQ|INE0BV301023', label: 'MAPMYINDIA' },
  { key: 'NSE_EQ|INE634S01028', label: 'MANKIND' },
  { key: 'NSE_EQ|INE113A01013', label: 'GNFC' },
  { key: 'NSE_EQ|INE742F01042', label: 'ADANIPORTS' },
  { key: 'NSE_EQ|INE278Y01022', label: 'CAMPUS' },
  { key: 'NSE_EQ|INE646L01027', label: 'INDIGO' },
  { key: 'NSE_EQ|INE271C01023', label: 'DLF' },
  { key: 'NSE_EQ|INE203A01020', label: 'ASTRAZEN' },
  { key: 'NSE_EQ|INE047A01021', label: 'GRASIM' },
  { key: 'NSE_EQ|INE208A01029', label: 'ASHOKLEY' },
  { key: 'NSE_EQ|INE501A01019', label: 'DEEPAKFERT' },
  { key: 'NSE_EQ|INE494B01023', label: 'TVSMOTOR' },
  { key: 'NSE_EQ|INE405E01023', label: 'UNOMINDA' },
  { key: 'NSE_EQ|INE031B01049', label: 'AJANTPHARM' },
  { key: 'NSE_EQ|INE0ONG01011', label: 'NTPCGREEN' },
  { key: 'NSE_EQ|INE481N01025', label: 'HOMEFIRST' },
  { key: 'NSE_EQ|INE721A01047', label: 'SHRIRAMFIN' },
  { key: 'NSE_EQ|INE933S01016', label: 'INDIAMART' },
  { key: 'NSE_EQ|INE338I01027', label: 'MOTILALOFS' },
  { key: 'NSE_EQ|INE095N01031', label: 'NBCC' },
  { key: 'NSE_EQ|INE931S01010', label: 'ADANIENSOL' },
  { key: 'NSE_EQ|INE018E01016', label: 'SBICARD' },
  { key: 'NSE_EQ|INE00WC01027', label: 'AFFLE' },
  { key: 'NSE_EQ|INE007A01025', label: 'CRISIL' },
  { key: 'NSE_EQ|INE061F01013', label: 'FORTIS' },
  { key: 'NSE_EQ|INE477A01020', label: 'CANFINHOME' },
  { key: 'NSE_EQ|INE180C01042', label: 'CGCL' },
  { key: 'NSE_EQ|INE031A01017', label: 'HUDCO' },
  { key: 'NSE_EQ|INE0V6F01027', label: 'HYUNDAI' },
  { key: 'NSE_EQ|INE457A01014', label: 'MAHABANK' },
  { key: 'NSE_EQ|INE127D01025', label: 'HDFCAMC' },
  { key: 'NSE_EQ|INE686F01025', label: 'UBL' },
  { key: 'NSE_EQ|INE883A01011', label: 'MRF' },
  { key: 'NSE_EQ|INE036D01028', label: 'KARURVYSYA' },
  { key: 'NSE_EQ|INE00H001014', label: 'SWIGGY' },
  { key: 'NSE_EQ|INE565A01014', label: 'IOB' },
  { key: 'NSE_EQ|INE849A01020', label: 'TRENT' },
  { key: 'NSE_EQ|INE758E01017', label: 'JIOFIN' },
  { key: 'NSE_EQ|INE531F01015', label: 'NUVAMA' },
  { key: 'NSE_EQ|INE383A01012', label: 'INDIACEM' },
  { key: 'NSE_EQ|INE726G01019', label: 'ICICIPRULI' },
  { key: 'NSE_EQ|INE101A01026', label: 'M&M' },
  { key: 'NSE_EQ|INE371A01025', label: 'GRAPHITE' },
  { key: 'NSE_EQ|INE280A01028', label: 'TITAN' },
  { key: 'NSE_EQ|INE274J01014', label: 'OIL' },
  { key: 'NSE_EQ|INE205B01031', label: 'ELECON' },
  { key: 'NSE_EQ|INE02ID01020', label: 'RAYMONDLSL' },
  { key: 'NSE_EQ|INE0W2G01015', label: 'SAGILITY' },
  { key: 'NSE_EQ|INE040A01034', label: 'HDFCBANK' },
  { key: 'NSE_EQ|INE481G01011', label: 'ULTRACEMCO' },
  { key: 'NSE_EQ|INE979A01025', label: 'SAREGAMA' },
  { key: 'NSE_EQ|INE040H01021', label: 'SUZLON' },
  { key: 'NSE_EQ|INE115A01026', label: 'LICHSGFIN' },
  { key: 'NSE_EQ|INE967H01025', label: 'KIMS' },
  { key: 'NSE_EQ|INE476A01022', label: 'CANBK' },
  { key: 'NSE_EQ|INE239A01024', label: 'NESTLE INDIA' },
  { key: 'NSE_EQ|INE575P01011', label: 'STARHEALTH' },
  { key: 'NSE_EQ|INE491A01021', label: 'CUB' },
  { key: 'NSE_EQ|INE818H01020', label: 'LTFOODS' },
  { key: 'NSE_EQ|INE825A01020', label: 'VTL' },
  { key: 'NSE_EQ|INE271B01025', label: 'MAHSEAMLES' },
  { key: 'NSE_EQ|INE0DYJ01015', label: 'SYRMA' },
  { key: 'NSE_EQ|INE414G01012', label: 'MUTHOOTFIN' },
  { key: 'NSE_EQ|INE211B01039', label: 'PHOENIXLTD' },
  { key: 'NSE_EQ|INE296A01024', label: 'BAJFINANCE' },
  { key: 'NSE_EQ|INE129A01019', label: 'GAIL' },
  { key: 'NSE_EQ|INE200M01039', label: 'VBL' },
  { key: 'NSE_EQ|INE733E01010', label: 'NTPC' },
  { key: 'NSE_EQ|INE335Y01020', label: 'IRCTC' },
  { key: 'NSE_EQ|INE660A01013', label: 'SUNDARMFIN' },
  { key: 'NSE_EQ|INE0NNS01018', label: 'NSLNISP' },
  { key: 'NSE_EQ|INE465A01025', label: 'BHARATFORG' },
  { key: 'NSE_EQ|INE702C01027', label: 'APLAPOLLO' },
  { key: 'NSE_EQ|INE059A01026', label: 'CIPLA' },
  { key: 'NSE_EQ|INE192A01025', label: 'TATACONSUM' },
  { key: 'NSE_EQ|INE674K01013', label: 'ABCAPITAL' },
  { key: 'NSE_EQ|INE438A01022', label: 'APOLLOTYRE' },
  { key: 'NSE_EQ|INE176B01034', label: 'HAVELLS' },
  { key: 'NSE_EQ|INE573A01042', label: 'JKTYRE' },
  { key: 'NSE_EQ|INE572A01036', label: 'JBCHEPHARM' },
  { key: 'NSE_EQ|INE139A01034', label: 'NATIONALUM' },
  { key: 'NSE_EQ|INE073K01018', label: 'SONACOMS' },
  { key: 'NSE_EQ|INE528G01035', label: 'YESBANK' },
  { key: 'NSE_EQ|INE347G01014', label: 'PETRONET' },
  { key: 'NSE_EQ|INE0J5401028', label: 'HONASA' },
  { key: 'NSE_EQ|INE010B01027', label: 'ZYDUSLIFE' },
  { key: 'NSE_EQ|INE213A01029', label: 'ONGC' },
  { key: 'NSE_EQ|INE084A01016', label: 'BANKINDIA' },
  { key: 'NSE_EQ|INE732A01036', label: 'KIRLOSBROS' },
  { key: 'NSE_EQ|INE776C01039', label: 'GMRAIRPORT' },
  { key: 'NSE_EQ|INE009A01021', label: 'INFY' },
  { key: 'NSE_EQ|INE120A01034', label: 'CARBORUNIV' },
  { key: 'NSE_EQ|INE256A01028', label: 'ZEEL' },
  { key: 'NSE_EQ|INE152A01029', label: 'THERMAX' },
  { key: 'NSE_EQ|INE437A01024', label: 'APOLLOHOSP' },
  { key: 'NSE_EQ|INE466L01038', label: '360ONE' },
  { key: 'NSE_EQ|INE548A01028', label: 'HFCL' },
  { key: 'NSE_EQ|INE685A01028', label: 'TORNTPHARM' },
  { key: 'NSE_EQ|INE842C01021', label: 'MINDACORP' },
  { key: 'NSE_EQ|INE03JT01014', label: 'GODIGIT' },
  { key: 'NSE_EQ|INE852O01025', label: 'APTUS' },
  { key: 'NSE_EQ|INE417T01026', label: 'POLICYBZR' },
  { key: 'NSE_EQ|INE343H01029', label: 'SOLARINDS' },
  { key: 'NSE_EQ|INE775A08105', label: 'MOTHERSON' },
  { key: 'NSE_EQ|INE944F01028', label: 'RADICO' },
  { key: 'NSE_EQ|INE752E01010', label: 'POWER GRID CORP' },
  { key: 'NSE|RVNL', label: 'RVNL' },
  { key: 'NSE|INDIANB', label: 'INDIANB' },
  { key: 'NSE|INTELLECT', label: 'INTELLECT' },
  { key: 'NSE_EQ|INE101A01026FIN', label: 'M&MFIN' },
  { key: 'NSE|PNCINFRA', label: 'PNCINFRA' },
  { key: 'NSE_EQ|INE066A01021', label: 'EICHER MOTORS' },
  { key: 'NSE|UNITDSPR', label: 'UNITDSPR' },
  { key: 'NSE|TRIDENT', label: 'TRIDENT' },
  { key: 'NSE|GSPL', label: 'GSPL' },
  { key: 'NSE|IDEA', label: 'IDEA' },
  { key: 'NSE|ADANIPOWER', label: 'ADANIPOWER' },
  { key: 'NSE_EQ|INE155A01022', label: 'TATA MOTORS' },
  { key: 'NSE|CDSL', label: 'CDSL' },
  { key: 'NSE|TANLA', label: 'TANLA' },
  { key: 'NSE|VMM', label: 'VMM' },
  { key: 'NSE|JUSTDIAL', label: 'JUSTDIAL' },
  { key: 'NSE|BIKAJI', label: 'BIKAJI' },
  { key: 'NSE|RAYMOND', label: 'RAYMOND' },
  { key: 'NSE|SIGNATURE', label: 'SIGNATURE' },
  { key: 'NSE|RITES', label: 'RITES' },
  { key: 'NSE|IDBI', label: 'IDBI' },
  { key: 'NSE|UCOBANK', label: 'UCOBANK' },
  { key: 'NSE_EQ|INE467B01029', label: 'TATA CONSULTANCY SERVICES' },
  { key: 'NSE|MANAPPURAM', label: 'MANAPPURAM' },
  { key: 'NSE|IOC', label: 'IOC' },
  { key: 'NSE|BRITANNIA', label: 'BRITANNIA' },
  { key: 'NSE|JMFINANCIL', label: 'JMFINANCIL' },
  { key: 'NSE|UTIAMC', label: 'UTIAMC' },
  { key: 'NSE|RBLBANK', label: 'RBLBANK' },
  { key: 'NSE_EQ|INE881D01027', label: 'ORACLE FINANCIAL SERVICES' },
  { key: 'NSE|MFSL', label: 'MFSL' },
  { key: 'NSE|DALBHARAT', label: 'DALBHARAT' },
  { key: 'NSE|JBMA', label: 'JBMA' },
  { key: 'NSE|RPOWER', label: 'RPOWER' },
  { key: 'NSE|SHREECEM', label: 'SHREECEM' },
  { key: 'NSE|WOCKPHARMA', label: 'WOCKPHARMA' },
  { key: 'NSE|EIHOTEL', label: 'EIHOTEL' },
  { key: 'NSE|RECLTD', label: 'REC' },
  { key: 'NSE_EQ|INE949L01017', label: 'AU SMALL FINANCE BANK' },
  { key: 'NSE|PRESTIGE', label: 'PRESTIGE' },
  { key: 'NSE_EQ|INE028A01039', label: 'BANK OF BARODA' },
  { key: 'NSE_EQ|INE154A01025', label: 'ITC' },
  { key: 'NSE|COLPAL', label: 'COLPAL' },
  { key: 'NSE|ESCORTS', label: 'ESCORTS' },
  { key: 'NSE_EQ|INE917I01010', label: 'BAJAJ AUTO' },
  { key: 'NSE|MCX', label: 'MCX' },
  { key: 'NSE|HINDZINC', label: 'HINDZINC' },
  { key: 'NSE_EQ|INE095A01012', label: 'INDUSIND BANK' },
  { key: 'NSE_EQ|INE160A01022', label: 'PUNJAB NATIONAL BANK' },
  { key: 'NSE|ANANTRAJ', label: 'ANANTRAJ' },
  { key: 'NSE|TIMKEN', label: 'TIMKEN' },
  { key: 'NSE|MAXHEALTH', label: 'MAXHEALTH' },
  { key: 'NSE|VOLTAS', label: 'VOLTAS' },
  { key: 'NSE|AMBUJACEM', label: 'AMBUJA CEMENTS' },
  { key: 'NSE_EQ|INE018A01030', label: 'LARSEN & TOUBRO' },
  { key: 'NSE|MMTC', label: 'MMTC' },
  { key: 'NSE_EQ|INE860A01027', label: 'HCL TECHNOLOGIES' },
  { key: 'NSE|LICI', label: 'LICI' },
  { key: 'NSE|RRKABEL', label: 'RRKABEL' },
  { key: 'NSE|OLECTRA', label: 'OLECTRA' },
  { key: 'NSE|CYIENT', label: 'CYIENT' },
  { key: 'NSE|IEX', label: 'IEX' },
  { key: 'NSE|GMDCLTD', label: 'GMDCLTD' },
  { key: 'NSE|NEULANDLAB', label: 'NEULANDLAB' },
  { key: 'NSE|JPPOWER', label: 'JPPOWER' },
  { key: 'NSE|SHYAMMETL', label: 'SHYAMMETL' },
  { key: 'NSE|IKS', label: 'IKS' },
  { key: 'NSE|BHEL', label: 'BHEL' },
  { key: 'NSE|LEMONTREE', label: 'LEMONTREE' },
  { key: 'NSE|BOSCHLTD', label: 'BOSCHLTD' },
  { key: 'NSE|GRANULES', label: 'GRANULES INDIA' },
  { key: 'NSE_EQ|INE089A01031', label: 'DR REDDY\'S LABS' },
  { key: 'NSE_EQ|INE795G01014', label: 'HDFC LIFE INSURANCE' },
  { key: 'NSE|IRB', label: 'IRB' },
  { key: 'NSE|BLS', label: 'BLS' },
  { key: 'NSE|BALKRISIND', label: 'BALKRISIND' },
  { key: 'NSE|ABFRL', label: 'ABFRL' },
  { key: 'NSE|DIXON', label: 'DIXON' },
  { key: 'NSE|PIDILITIND', label: 'PIDILITIND' },
  { key: 'NSE|BIOCON', label: 'BIOCON' },
  { key: 'NSE|TATAPOWER', label: 'TATAPOWER' },
  { key: 'NSE|DOMS', label: 'DOMS' },
  { key: 'NSE|PEL', label: 'PEL' },
  { key: 'NSE_EQ|INE356A01018', label: 'MPHASIS' },
  { key: 'NSE|TATAINVEST', label: 'TATAINVEST' },
  { key: 'NSE|JUBLPHARMA', label: 'JUBLPHARMA' },
  { key: 'NSE|KPIL', label: 'KPIL' },
  { key: 'NSE_EQ|INE263A01024', label: 'BHARAT ELECTRONICS' },
  { key: 'NSE|IRFC', label: 'IRFC' },
  { key: 'NSE|NMDC', label: 'NMDC' },
  { key: 'NSE|CENTRALBK', label: 'CENTRALBK' },
  { key: 'NSE|SKFINDIA', label: 'SKFINDIA' },
  { key: 'NSE|BRIGADE', label: 'BRIGADE' },
  { key: 'NSE|VEDL', label: 'VEDANTA' },
  { key: 'NSE|IGL', label: 'IGL' },
  { key: 'NSE|LLOYDSME', label: 'LLOYDSME' },
  { key: 'NSE|HAL', label: 'HAL' },
  { key: 'NSE_EQ|INE030A01027', label: 'HINDUSTAN UNILEVER' },
  { key: 'NSE|JWL', label: 'JWL' },
  { key: 'NSE|BANDHANBNK', label: 'BANDHANBNK' },
  { key: 'NSE|IIFL', label: 'IIFL' },
  { key: 'NSE|PVRINOX', label: 'PVRINOX' },
  { key: 'NSE|COCHINSHIP', label: 'COCHINSHIP' },
  { key: 'NSE|DATAPATTNS', label: 'DATAPATTNS' },
  { key: 'NSE|JSL', label: 'JINDAL STAINLESS' },
  { key: 'NSE|IFCI', label: 'IFCI' },
  { key: 'NSE|HONAUT', label: 'HONAUT' },
  { key: 'NSE_EQ|INE021A01026', label: 'ASIAN PAINTS' },
  { key: 'NSE_EQ|INE081A01020', label: 'TATA STEEL' },
  { key: 'NSE|BERGEPAINT', label: 'BERGEPAINT' },
  { key: 'NSE|AADHARHFC', label: 'AADHARHFC' },
  { key: 'NSE|NATCOPHARM', label: 'NATCOPHARM' },
  { key: 'NSE|PAGEIND', label: 'PAGEIND' },
  { key: 'NSE|RAILTEL', label: 'RAILTEL' },
  { key: 'NSE|SCI', label: 'SCI' },
  { key: 'NSE|HINDCOPPER', label: 'HINDUSTAN COPPER' },
  { key: 'NSE|DEVYANI', label: 'DEVYANI' },
  { key: 'NSE|RENUKA', label: 'RENUKA' },
  { key: 'NSE|GODREJIND', label: 'GODREJIND' },
  { key: 'NSE|HBLENGINE', label: 'HBLENGINE' },
  { key: 'NSE|DCMSHRIRAM', label: 'DCMSHRIRAM' },
  { key: 'NSE|NYKAA', label: 'NYKAA' },
  { key: 'NSE|POONAWALLA', label: 'POONAWALLA' },
  { key: 'NSE|CONCOR', label: 'CONCOR' },
  { key: 'NSE|GILLETTE', label: 'GILLETTE' },
  { key: 'NSE|GPPL', label: 'GPPL' },
  { key: 'NSE|FLUOROCHEM', label: 'FLUOROCHEM' },
  { key: 'NSE|ADANIGREEN', label: 'ADANIGREEN' },
  { key: 'NSE_EQ|INE171A01029', label: 'FEDERAL BANK' },
  { key: 'NSE|CESC', label: 'CESC' },
  { key: 'NSE|JKCEMENT', label: 'JKCEMENT' },
  { key: 'NSE|ACC', label: 'ACC' },
  { key: 'NSE|BLUEDART', label: 'BLUEDART' },
  { key: 'NSE|BSE', label: 'BSE' },
  { key: 'NSE_EQ|INE585B01010', label: 'MARUTI SUZUKI' },
  { key: 'NSE|PCBL', label: 'PCBL' },
  { key: 'NSE|RTNINDIA', label: 'RTNINDIA' },
  { key: 'NSE|LUPIN', label: 'LUPIN' },
  { key: 'NSE|OLAELEC', label: 'OLAELEC' },
  { key: 'NSE|WHIRLPOOL', label: 'WHIRLPOOL' },
  { key: 'NSE_EQ|INE423A01024', label: 'ADANI ENTERPRISES' },
  { key: 'NSE|MGL', label: 'MGL' },
  { key: 'NSE|LINDEINDIA', label: 'LINDEINDIA' },
  { key: 'NSE|TATACHEM', label: 'TATACHEM' },
  { key: 'NSE|ANANDRATHI', label: 'ANANDRATHI' },
  { key: 'NSE|SRF', label: 'SRF' },
  { key: 'NSE|SIEMENS', label: 'SIEMENS' },
  { key: 'NSE_EQ|INE522F01014', label: 'COAL INDIA' },
  { key: 'NSE|PFC', label: 'POWER FINANCE CORPORATION' },
  { key: 'NSE|LAURUSLABS', label: 'LAURUS LABS' },
  { key: 'NSE|ATGL', label: 'ATGL' },
  { key: 'NSE|IRCON', label: 'IRCON' },
  { key: 'NSE|SCHNEIDER', label: 'SCHNEIDER' },
  { key: 'NSE|HAPPSTMNDS', label: 'HAPPSTMNDS' },
  { key: 'NSE|CEATLTD', label: 'CEATLTD' },
  { key: 'NSE|METROPOLIS', label: 'METROPOLIS' },
  { key: 'NSE|RAMCOCEM', label: 'RAMCOCEM' },
  { key: 'NSE|INDHOTEL', label: 'INDHOTEL' },
  { key: 'NSE_EQ|INE019A01038', label: 'JSW STEEL' },
  { key: 'NSE|ANGELONE', label: 'ANGELONE' },
  { key: 'NSE_EQ|INE018A01030TS', label: 'LTTS' },
  { key: 'NSE|CUMMINSIND', label: 'CUMMINSIND' },
  { key: 'NSE|ALKEM', label: 'ALKEM LABORATORIES' },
  { key: 'NSE|FINPIPE', label: 'FINPIPE' },
  { key: 'NSE|ELGIEQUIP', label: 'ELGIEQUIP' },
  { key: 'NSE|MSUMI', label: 'MSUMI' },
  { key: 'NSE|SYNGENE', label: 'SYNGENE' },
  { key: 'NSE|ABBOTINDIA', label: 'ABBOTINDIA' },
  { key: 'NSE|BPCL', label: 'BPCL' },
  { key: 'NSE|POLYCAB', label: 'POLYCAB' },
  { key: 'NSE|TITAGARH', label: 'TITAGARH' },
  { key: 'NSE|ABREL', label: 'ABREL' },
  { key: 'NSE|BBTC', label: 'BBTC' },
  { key: 'NSE_EQ|INE158A01026', label: 'HERO MOTOCORP' },
  { key: 'NSE|JSWENERGY', label: 'JSWENERGY' },
  { key: 'NSE|TIINDIA', label: 'TIINDIA' },
  { key: 'NSE|NLCINDIA', label: 'NLCINDIA' },
  { key: 'NSE_EQ|INE669C01036', label: 'TECH MAHINDRA' },
  { key: 'NSE|AWL', label: 'AWL' },
  { key: 'NSE|GLAXO', label: 'GLAXO' },
  { key: 'NSE_EQ|INE038A01020', label: 'HINDALCO INDUSTRIES' },
  { key: 'NSE|PIIND', label: 'PIIND' },
  { key: 'NSE|APLLTD', label: 'APLLTD' },
  { key: 'NSE|KNRCON', label: 'KNRCON' },
  { key: 'NSE|KANSAINER', label: 'KANSAINER' },
  { key: 'NSE|AAVAS', label: 'AAVAS' },
  { key: 'NSE|GODREJCP', label: 'GODREJCP' },
  { key: 'NSE|ASAHIINDIA', label: 'ASAHIINDIA' },
  { key: 'NSE|FINCABLES', label: 'FINCABLES' },
  { key: 'NSE|CAMS', label: 'CAMS' },
  { key: 'NSE|ZENSARTECH', label: 'ZENSARTECH' },
  { key: 'NSE|GRSE', label: 'GRSE' },
  { key: 'NSE|DABUR', label: 'DABUR' },
  { key: 'NSE|EXIDEIND', label: 'EXIDEIND' },
  { key: 'NSE|BEML', label: 'BEML' },
  { key: 'NSE|NHPC', label: 'NHPC' },
  { key: 'NSE|MASTEK', label: 'MASTEK' },
  { key: 'NSE|SOBHA', label: 'SOBHA' },
  { key: 'NSE|ASTERDM', label: 'ASTERDM' },
  { key: 'NSE|BSOFT', label: 'BSOFT' },
  { key: 'NSE|WESTLIFE', label: 'WESTLIFE' },
  { key: 'NSE|KALYANKJIL', label: 'KALYANKJIL' },
  { key: 'NSE|OBEROIRLTY', label: 'OBEROIRLTY' },
  { key: 'NSE|SUPREMEIND', label: 'SUPREMEIND' },
  { key: 'NSE|NIVABUPA', label: 'NIVABUPA' },
  { key: 'NSE|TATATECH', label: 'TATATECH' },
  { key: 'NSE|NETWORK18', label: 'NETWORK18' },
  { key: 'NSE|JYOTHYLAB', label: 'JYOTHYLAB' },
  { key: 'NSE|FSL', label: 'FSL' },
  { key: 'NSE|WELSPUNLIV', label: 'WELSPUNLIV' },
  { key: 'NSE|JYOTICNC', label: 'JYOTICNC' },
  { key: 'NSE|INOXINDIA', label: 'INOXINDIA' },
  { key: 'NSE|CERA', label: 'CERA' },
  { key: 'NSE|GODREJPROP', label: 'GODREJPROP' },
  { key: 'NSE|BDL', label: 'BDL' },
  { key: 'NSE_EQ|INE092T01019', label: 'IDFC FIRST BANK' },
  { key: 'NSE|ATUL', label: 'ATUL' },
  { key: 'NSE|NAUKRI', label: 'NAUKRI' },
  { key: 'NSE|TRITURBINE', label: 'TRITURBINE' },
  { key: 'NSE|RAINBOW', label: 'RAINBOW' },
  { key: 'NSE|ASTRAL', label: 'ASTRAL' },
  { key: 'NSE|ABSLAMC', label: 'ABSLAMC' },
];

// List of stocks in NIFTY CPSE index
export const NIFTY_CPSE_STOCKS: InstrumentOption[] = [
  { key: 'NSE_EQ|INE095N01031', label: 'NBCC' },
  { key: 'NSE_EQ|INE274J01014', label: 'OIL' },
  { key: 'NSE_EQ|INE733E01010', label: 'NTPC' },
  { key: 'NSE_EQ|INE213A01029', label: 'ONGC' },
  { key: 'NSE_EQ|INE752E01010', label: 'POWERGRID' },
  { key: 'NSE_EQ|INE263A01024', label: 'BEL' },
  { key: 'NSE_EQ|INE704P01025', label: 'COCHINSHIP' },
  { key: 'NSE_EQ|INE522F01014', label: 'COALINDIA' },
  { key: 'NSE_EQ|INE589A01014', label: 'NLCINDIA' },
  { key: 'NSE_EQ|INE848E01016', label: 'NHPC' },
  { key: 'NSE_EQ|INE002L01015', label: 'SJVN' },
];

// List of stocks in NIFTY ENERGY index
export const NIFTY_ENERGY_STOCKS: InstrumentOption[] = [
  { key: 'NSE_EQ|INE844O01030', label: 'GUJGASLTD' },
  { key: 'NSE_EQ|INE117A01022', label: 'ABB' },
  { key: 'NSE_EQ|INE07Y701011', label: 'POWERINDIA' },
  { key: 'NSE_EQ|INE067A01029', label: 'CGPOWER' },
  { key: 'NSE_EQ|INE002A01018', label: 'RELIANCE' },
  { key: 'NSE_EQ|INE931S01010', label: 'ADANIENSOL' },
  { key: 'NSE_EQ|INE274J01014', label: 'OIL' },
  { key: 'NSE_EQ|INE040H01021', label: 'SUZLON' },
  { key: 'NSE_EQ|INE129A01019', label: 'GAIL' },
  { key: 'NSE_EQ|INE733E01010', label: 'NTPC' },
  { key: 'NSE_EQ|INE347G01014', label: 'PETRONET' },
  { key: 'NSE_EQ|INE213A01029', label: 'ONGC' },
  { key: 'NSE_EQ|INE152A01029', label: 'THERMAX' },
  { key: 'NSE_EQ|INE752E01010', label: 'POWERGRID' },
  { key: 'NSE_EQ|INE246F01010', label: 'GSPL' },
  { key: 'NSE_EQ|INE814H01011', label: 'ADANIPOWER' },
  { key: 'NSE_EQ|INE242A01010', label: 'IOC' },
  { key: 'NSE_EQ|INE614G01033', label: 'RPOWER' },
  { key: 'NSE_EQ|INE351F01018', label: 'JPPOWER' },
  { key: 'NSE_EQ|INE257A01026', label: 'BHEL' },
  { key: 'NSE_EQ|INE245A01021', label: 'TATAPOWER' },
  { key: 'NSE_EQ|INE203G01027', label: 'IGL' },
  { key: 'NSE_EQ|INE364U01010', label: 'ADANIGREEN' },
  { key: 'NSE_EQ|INE486A01021', label: 'CESC' },
  { key: 'NSE_EQ|INE002S01010', label: 'MGL' },
  { key: 'NSE_EQ|INE003A01024', label: 'SIEMENS' },
  { key: 'NSE_EQ|INE522F01014', label: 'COALINDIA' },
  { key: 'NSE_EQ|INE399L01023', label: 'ATGL' },
  { key: 'NSE_EQ|INE029A01011', label: 'BPCL' },
  { key: 'NSE_EQ|INE121E01018', label: 'JSWENERGY' },
  { key: 'NSE_EQ|INE589A01014', label: 'NLCINDIA' },
  { key: 'NSE_EQ|INE848E01016', label: 'NHPC' },
  { key: 'NSE_EQ|INE152M01016', label: 'TRITURBINE' },
  { key: 'NSE_EQ|INE094A01015', label: 'HINDPETRO' },
  { key: 'NSE_EQ|INE813H01021', label: 'TORNTPOWER' },
  { key: 'NSE_EQ|INE002L01015', label: 'SJVN' },
  { key: 'NSE_EQ|INE066P01011', label: 'INOXWIND' },
  { key: 'NSE_EQ|INE200A01026', label: 'GVT&D' },
  { key: 'NSE_EQ|INE172A01027', label: 'CASTROLIND' },
  { key: 'NSE_EQ|INE208C01025', label: 'AEGISLOG' },
];

// List of stocks in NIFTY INFRASTRUCTURE index
export const NIFTY_INFRASTRUCTURE_STOCKS: InstrumentOption[] = [
  { key: 'NSE_EQ|INE397D01024', label: 'BHARTIARTL' },
  { key: 'NSE_EQ|INE067A01029', label: 'CGPOWER' },
  { key: 'NSE_EQ|INE121J01017', label: 'INDUSTOWER' },
  { key: 'NSE_EQ|INE002A01018', label: 'RELIANCE' },
  { key: 'NSE_EQ|INE742F01042', label: 'ADANIPORTS' },
  { key: 'NSE_EQ|INE646L01027', label: 'INDIGO' },
  { key: 'NSE_EQ|INE271C01023', label: 'DLF' },
  { key: 'NSE_EQ|INE047A01021', label: 'GRASIM' },
  { key: 'NSE_EQ|INE208A01029', label: 'ASHOKLEY' },
  { key: 'NSE_EQ|INE481G01011', label: 'ULTRACEMCO' },
  { key: 'NSE_EQ|INE129A01019', label: 'GAIL' },
  { key: 'NSE_EQ|INE733E01010', label: 'NTPC' },
  { key: 'NSE_EQ|INE465A01025', label: 'BHARATFORG' },
  { key: 'NSE_EQ|INE213A01029', label: 'ONGC' },
  { key: 'NSE_EQ|INE437A01024', label: 'APOLLOHOSP' },
  { key: 'NSE_EQ|INE775A08105', label: 'MOTHERSON' },
  { key: 'NSE_EQ|INE752E01010', label: 'POWERGRID' },
  { key: 'NSE_EQ|INE242A01010', label: 'IOC' },
  { key: 'NSE_EQ|INE070A01015', label: 'SHREECEM' },
  { key: 'NSE_EQ|INE027H01010', label: 'MAXHEALTH' },
  { key: 'NSE_EQ|INE079A01024', label: 'AMBUJACEM' },
  { key: 'NSE_EQ|INE018A01030', label: 'LT' },
  { key: 'NSE_EQ|INE245A01021', label: 'TATAPOWER' },
  { key: 'NSE_EQ|INE364U01010', label: 'ADANIGREEN' },
  { key: 'NSE_EQ|INE003A01024', label: 'SIEMENS' },
  { key: 'NSE_EQ|INE053A01029', label: 'INDHOTEL' },
  { key: 'NSE_EQ|INE298A01020', label: 'CUMMINSIND' },
  { key: 'NSE_EQ|INE029A01011', label: 'BPCL' },
  { key: 'NSE_EQ|INE484J01027', label: 'GODREJPROP' },
  { key: 'NSE_EQ|INE094A01015', label: 'HINDPETRO' },
];

// List of stocks in NIFTY MNC index
export const NIFTY_MNC_STOCKS: InstrumentOption[] = [
  { key: 'NSE_EQ|INE117A01022', label: 'ABB' },
  { key: 'NSE_EQ|INE07Y701011', label: 'POWERINDIA' },
  { key: 'NSE_EQ|INE513A01022', label: 'SCHAEFFLER' },
  { key: 'NSE_EQ|INE208A01029', label: 'ASHOKLEY' },
  { key: 'NSE_EQ|INE007A01025', label: 'CRISIL' },
  { key: 'NSE_EQ|INE0V6F01027', label: 'HYUNDAI' },
  { key: 'NSE_EQ|INE686F01025', label: 'UBL' },
  { key: 'NSE_EQ|INE239A01024', label: 'NESTLEIND' },
  { key: 'NSE_EQ|INE572A01036', label: 'JBCHEPHARM' },
  { key: 'NSE_EQ|INE854D01024', label: 'UNITDSPR' },
  { key: 'NSE_EQ|INE216A01030', label: 'BRITANNIA' },
  { key: 'NSE_EQ|INE881D01027', label: 'OFSS' },
  { key: 'NSE_EQ|INE259A01022', label: 'COLPAL' },
  { key: 'NSE_EQ|INE042A01014', label: 'ESCORTS' },
  { key: 'NSE_EQ|INE325A01013', label: 'TIMKEN' },
  { key: 'NSE_EQ|INE079A01024', label: 'AMBUJACEM' },
  { key: 'NSE_EQ|INE323A01026', label: 'BOSCHLTD' },
  { key: 'NSE_EQ|INE068V01023', label: 'GLAND' },
  { key: 'NSE_EQ|INE640A01023', label: 'SKFINDIA' },
  { key: 'NSE_EQ|INE205A01025', label: 'VEDL' },
  { key: 'NSE_EQ|INE030A01027', label: 'HINDUNILVR' },
  { key: 'NSE_EQ|INE671A01010', label: 'HONAUT' },
  { key: 'NSE_EQ|INE585B01010', label: 'MARUTI' },
  { key: 'NSE_EQ|INE473A01011', label: 'LINDEINDIA' },
  { key: 'NSE_EQ|INE003A01024', label: 'SIEMENS' },
  { key: 'NSE_EQ|INE298A01020', label: 'CUMMINSIND' },
  { key: 'NSE_EQ|INE358A01014', label: 'ABBOTINDIA' },
  { key: 'NSE_EQ|INE470A01017', label: '3MINDIA' },
  { key: 'NSE_EQ|INE172A01027', label: 'CASTROLIND' },
  { key: 'NSE_EQ|INE03QK01018', label: 'SUVENPHAR' },
];

// List of stocks in NIFTY PSE index
export const NIFTY_PSE_STOCKS: InstrumentOption[] = [
  { key: 'NSE_EQ|INE274J01014', label: 'OIL' },
  { key: 'NSE_EQ|INE129A01019', label: 'GAIL' },
  { key: 'NSE_EQ|INE733E01010', label: 'NTPC' },
  { key: 'NSE_EQ|INE335Y01020', label: 'IRCTC' },
  { key: 'NSE_EQ|INE213A01029', label: 'ONGC' },
  { key: 'NSE_EQ|INE752E01010', label: 'POWERGRID' },
  { key: 'NSE_EQ|INE415G01027', label: 'RVNL' },
  { key: 'NSE_EQ|INE242A01010', label: 'IOC' },
  { key: 'NSE_EQ|INE020B01018', label: 'RECLTD' },
  { key: 'NSE_EQ|INE257A01026', label: 'BHEL' },
  { key: 'NSE_EQ|INE263A01024', label: 'BEL' },
  { key: 'NSE_EQ|INE053F01010', label: 'IRFC' },
  { key: 'NSE_EQ|INE584A01023', label: 'NMDC' },
  { key: 'NSE_EQ|INE066F01020', label: 'HAL' },
  { key: 'NSE_EQ|INE111A01025', label: 'CONCOR' },
  { key: 'NSE_EQ|INE522F01014', label: 'COALINDIA' },
  { key: 'NSE_EQ|INE134E01011', label: 'PFC' },
  { key: 'NSE_EQ|INE029A01011', label: 'BPCL' },
  { key: 'NSE_EQ|INE848E01016', label: 'NHPC' },
  { key: 'NSE_EQ|INE094A01015', label: 'HINDPETRO' },
];

// List of stocks in NIFTY FINANCIAL SERVICES EX-BANK index
export const NIFTY_FIN_SERVICES_EX_BANK_STOCKS: InstrumentOption[] = [];

// List of stocks in NIFTY COMMODITIES index
export const NIFTY_COMMODITIES_STOCKS: InstrumentOption[] = [];

// List of stocks in NIFTY INDIA CONSUMPTION index
export const NIFTY_INDIA_CONSUMPTION_STOCKS: InstrumentOption[] = [];

// List of stocks in NIFTY SERVICES SECTOR index
export const NIFTY_SERVICES_SECTOR_STOCKS: InstrumentOption[] = [];

// List of stocks in NIFTY INDIA DEFENCE index
export const NIFTY_INDIA_DEFENCE_STOCKS: InstrumentOption[] = [];

// List of stocks in NIFTY INDIA TOURISM index
export const NIFTY_INDIA_TOURISM_STOCKS: InstrumentOption[] = [];

// List of stocks in NIFTY CAPITAL MARKETS index
export const NIFTY_CAPITAL_MARKETS_STOCKS: InstrumentOption[] = [];

// List of stocks in NIFTY CONSUMER DURABLES index
export const NIFTY_CONSUMER_DURABLES_STOCKS: InstrumentOption[] = [];

// List of stocks in NIFTY OIL & GAS index
export const NIFTY_OIL_GAS_STOCKS: InstrumentOption[] = [];

// Maps of index names to their corresponding stocks list
export const INDEX_TO_STOCKS: Record<string, InstrumentOption[]> = {
  "Nifty 50": NIFTY_50_STOCKS,
  "Nifty Bank": NIFTY_PRIVATE_BANK_STOCKS,
  "Nifty IT": NIFTY_IT_STOCKS,
  "Nifty Pharma": NIFTY_PHARMA_STOCKS,
  "Nifty Metal": NIFTY_METAL_STOCKS,
  "Nifty Fin Service": NIFTY_FIN_SERVICES_STOCKS,
  "Nifty FMCG": NIFTY_FMCG_STOCKS,
  "Nifty Media": NIFTY_MEDIA_STOCKS,
  "Nifty PSU Bank": NIFTY_PSU_BANK_STOCKS,
  "Nifty Private Bank": NIFTY_PRIVATE_BANK_STOCKS,
  "Nifty Realty": NIFTY_REALTY_STOCKS,
  "Nifty Healthcare": NIFTY_HEALTHCARE_STOCKS,
  "Nifty 500": NIFTY_500_STOCKS,
  "Nifty Consumer Durables": NIFTY_CONSUMER_DURABLES_STOCKS,
  "Nifty OIL & GAS": NIFTY_OIL_GAS_STOCKS,
  "Nifty Fin Service Ex-Bank": NIFTY_FIN_SERVICES_EX_BANK_STOCKS,
  "Nifty Commodities": NIFTY_COMMODITIES_STOCKS,
  "Nifty India Consumption": NIFTY_INDIA_CONSUMPTION_STOCKS,
  "Nifty CPSE": NIFTY_CPSE_STOCKS,
  "Nifty Energy": NIFTY_ENERGY_STOCKS,
  "Nifty Infrastructure": NIFTY_INFRASTRUCTURE_STOCKS,
  "Nifty MNC": NIFTY_MNC_STOCKS,
  "Nifty PSE": NIFTY_PSE_STOCKS,
  "Nifty Services Sector": NIFTY_SERVICES_SECTOR_STOCKS,
  "Nifty India Defence": NIFTY_INDIA_DEFENCE_STOCKS,
  "Nifty India Tourism": NIFTY_INDIA_TOURISM_STOCKS,
  "Nifty Capital Markets": NIFTY_CAPITAL_MARKETS_STOCKS,
  // More indices will be added as needed
};


// Helper function to get stocks for a specific index
export function getStocksForIndex(indexName: string): InstrumentOption[] {
  return INDEX_TO_STOCKS[indexName] || [];
}